DO NOT REVIEW YET feat: box shadow support in deep landscape
Financial-Times/origami pull request #1008
Opened 2023-02-16 15:09 UTC by umbobabo

We are introducing a Box Shadow variation for the deep landscape layout in toppers.

In this PR:

* Add new box shadow modifier
* Fix the credit not appearing in the Deep Landscape demo
* Extending the existing demo to cover more permutation of the components

2023-02-27 11:51 UTC, notlee approved these changes
@umbobabo Approving the CSS changes 👍 However do you think we could instead release `o-topper__content--text-shadow`? 

Picking between nothing, `text-shadow`, and `box-shadow` feels like an onerous decision to place on editorial. They'd need to pick from 3 options keeping in mind contrast requirements at multiple viewport sizes, and for screens that provide less good contrast to out work machines. 

Reducing to 2 options (nothing or the box shadow style) is an easier and less nuanced decision to have to make.

2023-03-02 11:09 UTC, umbobabo commented
> Picking between nothing, `text-shadow`, and `box-shadow` feels like an onerous decision to place on editorial. They'd need to pick from 3 options keeping in mind contrast requirements at multiple viewport sizes, and screens that provide less good contrast than our work machines.
> 
> Reducing to 2 options (nothing or the box shadow style) is an easier and less nuanced decision to have to make.

Thank you for the feedback.
I appreciate what you are saying, but at the same time, we see a push in the composition of very different pages with different looks and feels, like HTSI that are leading towards integrating more capabilities in Spark UI.
The requested changes went through the review process in Spark with Editorial, and they have been discussed and approved, so I would rather not challenge them at this stage.

If you have concerns about the direction this is taking (and that is understandable) let's have a chat and see if we should be more careful about accepting these kinds of changes.

I pushed an additional change that just enforces the bottom margin on mobile too for this new modifier via higher specific of the selector.

![image](https://user-images.githubusercontent.com/752680/222411753-e655f924-c1eb-45fc-acd2-0f0c43d4f5f1.png)

2023-03-02 11:34 UTC, juanSanchezAlcala reviewed
Shouldn't we set the color of the text based on the background-box-colors in case it has ? Or it is posible to have backround dark and text black ? If not i would add also 
`color: if($background-box-color == 'dark', rgb(255,255,255), rgb(18,18,18,0.4));`

2023-03-02 12:03 UTC, umbobabo commented
> Shouldn't we set the color of the text based on the background-box-colors in case it has ? Or it is posible to have backround dark and text black ? If not i would add also `color: if($background-box-color == 'dark', rgb(255,255,255), rgb(18,18,18,0.4));`

The text color logic is quite [tangled with the background colour](https://github.com/Financial-Times/origami/blob/3eb60451d48f5f323f9b97c228f71e0b4b3c7161/components/o-topper/src/scss/_mixins.scss#L254), to change this logic only for deep landscape would mean change quite a lot of stuff given the way [all the topper are created from the same mixing](https://github.com/Financial-Times/origami/blob/3eb60451d48f5f323f9b97c228f71e0b4b3c7161/components/o-topper/main.scss#L50) that split colours to theme part.

I can have a better look, but my solution was to [force the background colour when there is a background box](https://github.com/Financial-Times/n-map-content-to-topper/pull/41).

2023-03-02 12:18 UTC, juanSanchezAlcala approved these changes

2023-03-03 08:51 UTC, notlee requested changes
@umbobabo I would like us to ask Editorial if they intend to use both `text-shadow` and `background-box` styles, or if `background-box` means we can deprecate `text-shadow`.

Originally Deep Portrait had neither style. [Origami suggested design changes to improve readability](https://github.com/Financial-Times/origami/pull/929#pullrequestreview-1222438509). We worked with Jazmin to propose 2 options (text-shadow and background-box). DAC recommended background-box as did Origami, but editorial chose to go with text-shadow. Now box-shadow is being added. I'd like to know if they have changed their mind (as text-shadow isn't very effective) or if they actually would like to use both. 

I'm happy either way but want to make sure we're removing options which aren't intended to be used and associated tech debt.

2023-03-03 08:51 UTC, notlee commented on components/o-topper/src/scss/themes/_deep-landscape.scss
> +		.o-topper__content.o-topper__content--background-box-#{$background-box-color} {
The demo is broken as this new class hasn't been applied. Although the commit mentions "add margin on mobile resolution increasing specificity" but I'm not seeing any difference from before, there didn't seem to be a specificity issue.

<img width="1440" alt="Screenshot 2023-03-03 at 08 40 38" src="https://user-images.githubusercontent.com/10405691/222673321-6dcf135b-2083-4787-8523-16dbe4ca8664.png">

The new approach makes the markup / templating more complex and introduces scope for errors as the right `background-box` class has to be set for the right colour. I prefer your previous approach which aligns with how `text-shadow` is applied. Could we stick with your previous approach unless there's a good reason for the new classes I'm not seeing?

2023-03-03 13:14 UTC, umbobabo commented
> @umbobabo I'm totally not opposed to this new style (it's better). I would like us to ask Editorial if they intend to use both `text-shadow` and `background-box` styles, or if `background-box` means we can deprecate `text-shadow`.
> 
> Originally Deep Portrait had neither style. [Origami suggested design changes to improve readability](https://github.com/Financial-Times/origami/pull/929#pullrequestreview-1222438509). We worked with Jazmin to propose 2 options (text-shadow and background-box). DAC recommended background-box as did Origami, but editorial chose to go with text-shadow. Now box-shadow is being added. I'd like to know if they have changed their mind (as text-shadow isn't very effective) or if they actually would like to use both.
> 
> I'm happy either way but want to make sure we're removing options which aren't intended to be used, along with tech debt associated with maintaining many permutations of a design in both code and design tooling.

It totally makes sense to me. I have raised this discussion in StoryTelling Stand Up this morning and I will keep you in the loop.

2023-03-03 13:20 UTC, umbobabo commented on components/o-topper/src/scss/themes/_deep-landscape.scss
> +		.o-topper__content.o-topper__content--background-box-#{$background-box-color} {
I decided to revert to the previous approach as you mentioned, which also fixed the demo, let me know what you think.

This is how things look now after a rebase on the latest version of Origami

![image](https://user-images.githubusercontent.com/752680/222729889-ac7e125a-74c6-4f66-927e-97fc019b0bda.png)

![image](https://user-images.githubusercontent.com/752680/222730246-c0240eca-0e30-494d-89c3-a46d4197b23a.png)

![image](https://user-images.githubusercontent.com/752680/222730333-89bab6e2-366e-4c4a-aef4-2fc78e8b60d0.png)

![image](https://user-images.githubusercontent.com/752680/222730386-5fbb02df-b953-48ce-bc19-42df2c3a8768.png)

2023-03-06 11:14 UTC, notlee commented
Cool, I've approved that @umbobabo from a code perspective. I've just updated [the Jira ticket](https://financialtimes.atlassian.net/browse/CI-1543?focusedCommentId=679680) with the context I shared here too regarding potentially deprecating the text shadow

2023-03-06 16:23 UTC, merged