feat: options can be rendered as already selected OR-184
Financial-Times/origami pull request #1094
Opened 2023-04-25 09:55 UTC by akomiqaia

2023-04-25 10:00 UTC, notlee requested changes
Nice work fixing this quickly for Marlon :) It would be good to add tests for this also

2023-04-25 10:00 UTC, notlee commented on components/o-multi-select/src/tsx/multi-select.tsx
> +	multiSelectOptions: MultiSelectType[];
This is a breaking change. We need to release a new major or support both `string[]` and `MultiSelectType[]`

2023-04-25 10:00 UTC, notlee commented on components/o-multi-select/src/js/multi-select-options.js
> +	optionEl.setAttribute('aria-selected', selected);
I think this should be true/false?
https://developer.mozilla.org/en-US/docs/Web/API/Element/ariaSelected#value

2023-04-25 14:54 UTC, notlee requested changes
You also need to write a Migration Guide and update the table in the README to release a major. Both work, but probably it would be easier to support both TSX interfaces 😀

2023-04-27 13:35 UTC, frshwtr commented
Note from pairing: The enhanced experience doesn't update the core values when selected. Ideally it should do this if a form gets submitted off the back of this.

2023-05-02 10:09 UTC, notlee approved these changes

2023-05-02 10:12 UTC, merged