or-227: add o-editorial-typography links styles
Financial-Times/origami pull request #1296
Opened 2023-10-06 13:02 UTC by npelvinft

## Describe your changes
Added o-editorial-typography links styles for standard and inverse.
Added relevant demos.

## Issue ticket number and link
Jira ticket [OR-227](https://financialtimes.atlassian.net/browse/OR-227)

## Link to Figma designs
[Figma Link](https://www.figma.com/file/MyHQ1qdwYyek5IBdhEEaND/FT-UI-Library?type=design&node-id=0-1433&mode=design).

## Checklist before requesting a review
- [ ] I have applied `percy` label on my PR before merging and after review.
- [ ] If it is a new feature, I have added thorough tests.
- [ ] I have updated relevant docs.

2023-10-09 13:39 UTC, notlee requested changes

2023-10-09 13:39 UTC, notlee commented on components/o-editorial-typography/demos/src/professional-links-inverse.mustache
> +    Links may open in a new window/tab but we <a href="https://www.w3.org/TR/WCAG20-TECHS/G200.html" class="o-editorial-typography-link">recommend against this</a> in most cases.
`professional-links-inverse.mustache` and `professional-links.mustache` isn't used and may be deleted.

2023-10-09 13:39 UTC, notlee commented on components/o-editorial-typography/main.scss
> +		.o-editorial-typography--inverse {
Did you mean to name this `o-editorial-typography-body--inverse`, as a modifier of `o-editorial-typography`?

2023-10-09 13:39 UTC, notlee commented on components/o-editorial-typography/main.scss
> +			--_o-typography-link-color: #{_oEditorialTypographyGet('base', 'link-inverse')};
The `_` here indicates this is a private CSS custom property to o-typography, which shouldn't be dependent. Private properties allow us to refactor freely without causing breaking changes. We either need to use an existing public API such as `oTypographyLink` or update these Custom Properties in o-typography to be public, and document the usecase in o-typography's README.

2023-10-09 13:39 UTC, notlee commented on components/o-editorial-typography/src/scss/_brand.scss
> +			'ft-live'
Some things to tidy up here. It doesn't look like `link`, `link-professional`, `link-professional-inverse`. `professional`, or `ft-live` keys are used. Can they be deleted.

2023-10-09 13:39 UTC, notlee commented on components/o-editorial-typography/src/scss/_mixins.scss
> +  	// stylelint-disable-next-line declaration-block-no-duplicate-properties -- to provide a css custom property fallback
We can avoid this warning rather than disable is, as CSS Custom Properties accept a fallback value

`color:  var(--_o-editorial-typography-body-color, #{oColorsByUsecase('body', 'text')});`

2023-10-09 13:39 UTC, notlee commented on components/o-typography/main.scss
> -			--_o-typography-body-color: #{oColorsByName('white')};
👍

2023-10-12 10:04 UTC, npelvinft commented on components/o-editorial-typography/main.scss
> +			--_o-typography-link-color: #{_oEditorialTypographyGet('base', 'link-inverse')};
Thanks Lee, have used your first suggestion.

2023-10-16 09:01 UTC, notlee approved these changes

2023-10-16 09:34 UTC, merged