Experiment with build step
Financial-Times/origami pull request #1298
Opened 2023-10-09 15:49 UTC by akomiqaia

## Describe your changes
- creates a build script for o3-components
  build script 
    - builds tokens for the component
    - transpiles tsx to jsx
    - bundles css
- updates css token destinations for the component

2023-10-16 11:04 UTC, notlee requested changes

2023-10-16 11:04 UTC, notlee commented on tools/o3-compilation/index.js
> +esbuild.build({
o3-button uses `appearance` and `mask` so we need PostCSS with the [autoprefixer](https://github.com/postcss/autoprefixer) plugin for cross-browser support. We'll also need the [postcss-nesting](https://www.npmjs.com/package/postcss-nesting) in the future so we can continue to nest CSS with support for all our browsers.

2023-10-16 11:04 UTC, notlee commented on tools/o3-compilation/index.js
> +	external: ["@financial-times/o3-web-token/*", "*/main.css"],
Would `@financial-times/*` work to exclude any FT dependency?

2023-10-16 13:20 UTC, frshwtr commented on apps/dictionary/scripts/build-config/build-component.js
>  		const sources = [`tokens/${brandName}/components/${componentName}.json`]
There's a few things going on in this folder:
* Storage of design tokens
* Storage and execution of token build scripts
* Storage for Tokens Studio-specific configuration

`app` seemed most appropriate at the time due to the multi-function of the tokens. `dictionary` is fine though we lose some semantics from the category directories.

I think whichever we go for, the contents of `apps/dictionary` should remain under one directory as the building/configuration is exclusively specific to tokens and is not shared between other parts of Origami.

> Would this be better within a root `/dictionary` or similar?

This would work though we lose some semantic meaning from the apps/components/libraries.

> Looks like there's already a root /tokens folder that may be redundant?

This is correct.

2023-10-16 14:46 UTC, frshwtr commented on components/o3-button/package.json
> +		"@financial-times/o3-web-token": "file:../o3-web-token"
As its a dependency, it should be released before this. Is there a PR to release web token?

2023-10-16 14:47 UTC, frshwtr commented on components/o3-button/src/css/css-brands/core.css
> +@import '@financial-times/o3-web-token/core/_variables.css';
`css` in `css-brands` seems redundant given we're already in the `css` directory. Can it be shortened to `brands`?

2023-10-16 15:46 UTC, akomiqaia commented on components/o3-button/package.json
> +		"css"
yes, I believe it will include them. which we don't need I guess and it should be just a build folder.

2023-10-16 15:48 UTC, akomiqaia commented on scripts/component/build-o3.bash
> +if test -f "build.config.mjs"; then
it does not but it could if you wanted to have a custom build step for certain components.

2023-10-16 15:56 UTC, akomiqaia commented on scripts/component/build-o3.bash
> +if test -f "build.config.mjs"; then
or do we think this should be added later if we wanted to and we should not overengineer?

2023-10-16 15:57 UTC, akomiqaia commented on scripts/component/build-o3.bash
> +fi
no examples. this might be over engineering as well

2023-10-16 15:57 UTC, notlee commented on apps/dictionary/scripts/build-config/build-component.js
>  		const sources = [`tokens/${brandName}/components/${componentName}.json`]
Thanks, I agree we can talk about it separately. I think we're working under different definitions of app vs. library vs. whatever, so we should spend some time to agree on a definition and write them down

2023-10-16 15:57 UTC, notlee commented on apps/dictionary/scripts/build-config/build-component.js
>  		const sources = [`tokens/${brandName}/components/${componentName}.json`]
I guess for now, we just need to delete the root tokens folder

2023-10-16 15:59 UTC, notlee commented on components/o3-button/package.json
> +		"@financial-times/o3-web-token": "file:../o3-web-token"
We shouldn't need to release this first to update package.json, as it's within an npm workspace? Perhaps we do need to update `@financial-times/o3-web-token/package.json` with a version though

2023-10-16 15:59 UTC, notlee commented on components/o3-button/package.json
> +		"css"
I think so 👍 let's update this to only include the build folder

2023-10-16 16:20 UTC, akomiqaia commented on components/o3-button/package.json
> +		"@financial-times/o3-web-token": "file:../o3-web-token"
I don't think it will work. [NPM publish does not include symbolic links](https://docs.npmjs.com/cli/v9/commands/npm-publish) 
```https://docs.npmjs.com/cli/v9/commands/npm-publish```

2023-10-17 08:37 UTC, notlee commented on components/o3-button/package.json
> +		"@financial-times/o3-web-token": "file:../o3-web-token"
We'll still be publishing o3-web-token first or at the same time as o3-button.  We can use workspaces to depend on o3-web-token before it's published. Then we won't need to remember to update o3-button's package.json when it's deployed:
https://docs.npmjs.com/cli/v8/using-npm/workspaces#adding-dependencies-to-a-workspace

I've pushed a commit for that

2023-10-17 08:46 UTC, notlee approved these changes
nice work

2023-10-17 10:05 UTC, merged