O3 tooltip
Financial-Times/origami pull request #1429
Opened 2024-02-07 15:42 UTC by akomiqaia

## Describe your changes
- creates o3-tooltip component using web component API.

2024-02-19 12:55 UTC, akomiqaia commented on .vscode/settings.json
> +  "typescript.tsdk": "node_modules/typescript/lib"
ups. I think vscode doest this by default anyway.

2024-02-19 12:56 UTC, akomiqaia commented on .release-please-manifest.json
> -{"components/ft-concept-button":"1.2.3","components/g-audio":"2.0.3","components/n-notification":"8.2.6","components/o-audio":"2.1.4","components/o-autocomplete":"1.9.1","components/o-banner":"4.5.2"
I think npm run generate also changes this file?

2024-02-19 12:56 UTC, akomiqaia commented on components/o3-tooltip/README.md
> +- [Usage](#usage)
yeah of course. I am gonna write a new readme for o3-tooltip

2024-02-19 17:10 UTC, notlee commented on components/o3-tooltip/README.md
> +`o3-tooltip` currently supports two variants, which is determined by `render-on-open` attribute on custom element. If attribute is enable the tooltip will be rendered once the DOM is loaded and will
`render-on-open` is a behaviour driven API. This reminds me of the `o-tooltip` API where it was possible to configure lots of behaviours. However, that lead to lots of misuse.

It's difficult to talk communicate the "tooltip without render-on-open enabled" vs. "toggletip", making design/engineer collaboration potentially confusing. In addition, this API may be less flexible. What if we want to change the behaviour of one of our tooltip variants? Or introduce a 3rd tooltip usecase.

An API that focuses on what the tooltip usecase is, rather than how it behaves, may be more appropriate. You previously suggested a `type` property, or breaking out into a separate component, could that improve on the points above?

2024-02-19 17:10 UTC, notlee commented on components/o3-tooltip/README.md
> +`o3-tooltip` currently supports two variants, which is determined by `render-on-open` attribute on custom element. If attribute is enable the tooltip will be rendered once the DOM is loaded and will
Related, to support the design/engineer workflow ideally naming would be reflected in Figma – same props / component name. Deyan currently documents `o3-toggletip` and `o3-tooltip` but only has 1 Figma component `o3-tooltip` because they look the same. How do we ensure the alignment for smooth handover via dev mode?

https://www.figma.com/file/5ATknbGociZMlnNXX4sy4f/%F0%9F%92%A0-Whitelabel---Design-System?type=design&node-id=4192-618&mode=design&t=5RiBObebw6oEo8Gv-4

2024-02-19 17:16 UTC, notlee commented on components/o3-tooltip/README.md
> +### Branding
This is true for every component. We try to avoid duplicating general component use across READMEs. I've onboard with keeping it whilst we have few components though. Where should this content live in the future? A guide on the for everyone site maybe

2024-02-19 17:16 UTC, notlee commented on components/o3-tooltip/README.md
> +import '@financial-times/o3-tooltip/css/whitelabel.css';
```suggestion
import '@financial-times/o3-tooltip/css/[your brand].css';
```
?

2024-02-19 17:18 UTC, notlee commented on components/o3-tooltip/README.md
> +`o3-tooltip` has a JSX component exported as well. To use it, you can use the following code:
Woop! Glad we're documenting JSX. This is new to most people! Should it come first, above Markup? Or perhaps as part of it, so long as we make the 2 options clear. I think we'd like to encourage more template use.

2024-02-19 17:21 UTC, notlee commented on components/o3-tooltip/main.css
> +@font-face {
We're defining this font-face multiple times now, in o3-button and o3-tooltip. Where should it live? 

I think I'd live to avoid `o3-fonts` because I don't think it has much benefit being so granular over something like `o3-foundations`. Problems with that though include out token build pipeline which currently assumes component design tokens live within a component directory of the same name.

2024-02-19 17:21 UTC, notlee commented on components/o3-tooltip/main.css
> +	--_o3-tooltip-close-button-size: var(--o3-spacing-xs);
Nice mapping here

2024-02-19 17:21 UTC, notlee commented on components/o3-tooltip/main.css
> +	z-index: 10;
How did you choose an appropriate z-index?

2024-02-19 17:22 UTC, notlee commented on components/o3-tooltip/main.css
> +	/* TODO: Values are copied from figma but this can be replaced by tokens */
Is that todo for now or a hope for the future?

2024-02-19 17:22 UTC, notlee commented on components/o3-tooltip/main.css
> +	font-size: 14px;
We have design tokens for all of these values – we should use them as we expect users to, to ensure we're keeping to our own design rules

2024-02-19 17:24 UTC, notlee commented on components/o3-tooltip/main.css
> +	font-weight: inherit;
these are already inherited?
https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#formal_definition

2024-02-19 17:25 UTC, notlee commented on components/o3-tooltip/README.md
> +    <div class="o3-tooltip-content-title">Title</div>
It would be good to explain more what title is and when to use it. I believe there is an accessibility concern here in that we can't emphasis the "title" to screen reader users, so we should be clear that this distinction is presentational only and copy should be written accordingly. Perhaps Deyan can help write those guidelines

2024-02-19 17:26 UTC, notlee commented on components/o3-tooltip/main.css
> +	margin-bottom: 8px;
Same here on using our own tokens (maybe elsewhere, I'll stop flagging that)

2024-02-19 17:26 UTC, notlee commented on components/o3-tooltip/main.css
> +	background-color: var(--o3-color-palette-black-30);
Tokens! 🎉

2024-02-19 17:27 UTC, notlee commented on components/o3-tooltip/main.css
> +@keyframes bounce-top {
The bounce has grown on me. It didn't feel very on brand at first, but, I buy it now

2024-02-19 17:30 UTC, notlee commented on components/o3-tooltip/src/css/tokens/core/professional/o3-tooltip/_variables.css
> +
FT Professional currently use slate tooltips. Are we removing that on purpose or just something missed?
https://main--655f72ec522e424302dc6201.chromatic.com/?path=/story/o2-core_components-o-tooltip-professional-demo--professional-demo&globals=backgrounds:!undefined

2024-02-19 17:31 UTC, notlee commented on components/o3-tooltip/src/ts/tooltip.ts
> +	private getTargetNode() {
Should all the other functions / properties be private also or do we have a reason to expose them?

2024-02-19 17:35 UTC, notlee commented on components/o3-tooltip/src/ts/tooltip.ts
> +			this._closeButton.remove();
Under what scenario is there a close button to remove here?

2024-02-19 17:39 UTC, notlee commented on components/o3-tooltip/stories/core/tooltip.stories.tsx
> +	HoverToolTip as HoverToolTipStory,
I believe we agreed to implement a classic toggle tip without triggering on focus/click, and not hover?

This gives a a slightly weird experience when opened with focus and closed with hover:
https://github.com/Financial-Times/origami/assets/10405691/d7ee49e8-e214-4ac3-9af0-86c07f4ecbfc

2024-02-19 17:40 UTC, notlee commented on components/o3-tooltip/stories/demo.css
> +	position: absolute;
Is this CSS loaded only for the o3 demo? If not we should namespace it

2024-02-19 17:45 UTC, notlee commented on components/o3-tooltip/src/ts/tooltip.ts
> +			placement: this.placement,
It's very likely a tooltip's placement will need to vary according to the viewport size. o-tooltip took placement as a preference, but would fallback to a different placement if required. o3-tooltip just gets cut off:

https://github.com/Financial-Times/origami/assets/10405691/ab7ccf21-4d24-4bee-8854-7e66900bae27

Is there a way we can place o3-tooltip to fit, if the configured placement overflows?

2024-02-19 17:49 UTC, notlee commented on tsconfig.json
> +		"target": "ES2021",
As discussed, we'll review this as a team

2024-02-20 09:31 UTC, akomiqaia commented on components/o3-tooltip/stories/demo.css
> +	position: absolute;
yes, it is. it's loaded in only the storybook.

2024-02-20 10:46 UTC, wheresrhys commented on components/o3-tooltip/main.css
> +@keyframes bounce-top {
Has Darci seen the bounce?

2024-02-20 10:48 UTC, wheresrhys commented on components/o3-tooltip/main.css
> +		transform: translateY(-30px);
Could these be rewritten with less repetition using

```css
--bounce-horizontal-offset: 30px
--bounce-vertical-offset: 15px
```
Then use calc with +/-1 ?

2024-02-20 10:50 UTC, wheresrhys commented on components/o3-tooltip/main.css
> +		transform: translateY(-30px);
Similarly, even though it's actually more characters, could put the keyframe % values in variables

2024-02-20 10:50 UTC, akomiqaia commented on components/o3-tooltip/src/ts/tooltip.ts
> +			placement: this.placement,
[30208f4](https://github.com/Financial-Times/origami/pull/1429/commits/30208f4c7359656a229ce413cbb9974e2aef4806)

2024-02-20 11:07 UTC, akomiqaia commented on components/o3-tooltip/main.css
> +		transform: translateY(-30px);
maybe `--bounce-offset: 30px` and use calc to divide it by 2 would work better? 

Both horizontal and vertical values have the same but transform either x or y axis. 

what do you think about this?
[e8364ae](https://github.com/Financial-Times/origami/pull/1429/commits/e8364ae314d82108c5db2c7b3d61cb0df60dd64f)

2024-02-20 11:14 UTC, wheresrhys commented on components/o3-tooltip/main.css
> +		transform: translateY(-30px);
Yep that feels a lot more design systemy to me now

2024-02-20 11:34 UTC, akomiqaia commented on components/o3-tooltip/README.md
> +### Branding
[ee07873](https://github.com/Financial-Times/origami/pull/1429/commits/ee07873859c69920cd65c9f2811b65a5c825e319) Yeah I agree and we should have a more generic page on o4e page to tell users how to implement branding.

2024-02-20 11:36 UTC, akomiqaia commented on components/o3-tooltip/README.md
> +import '@financial-times/o3-tooltip/css/whitelabel.css';
[cd7ca27](https://github.com/Financial-Times/origami/pull/1429/commits/cd7ca27b7d9f66f7f9b99c259faea7bce8e69d75) updated all mentions of whitelabel.

2024-02-20 11:36 UTC, akomiqaia commented on components/o3-tooltip/main.css
> +	/* TODO: Values are copied from figma but this can be replaced by tokens */
it's more of a hope

2024-02-20 11:46 UTC, akomiqaia commented on components/o3-tooltip/main.css
> +@font-face {
can we maybe write a custom transformer for this to include `@font-face` inside the brand CSS file?

2024-02-20 11:47 UTC, akomiqaia commented on components/o3-tooltip/main.css
> +	z-index: 10;
This was generated from our SaSS build.

2024-02-20 11:48 UTC, akomiqaia commented on components/o3-tooltip/main.css
> +	font-size: 14px;
I saw this as temp solution until fonts are defined for brands and I thought they would go inside the o3-web-token package that generates brand specific class and font faces?

2024-02-20 11:52 UTC, akomiqaia commented on components/o3-tooltip/src/css/tokens/core/professional/o3-tooltip/_variables.css
> +
I guess this is what I mean by some tokens need to come from Figma? we should define `o3-tooltip-background-color` or something similar that can be used later on in our code.

2024-02-20 11:54 UTC, akomiqaia commented on components/o3-tooltip/src/ts/tooltip.ts
> +			this._closeButton.remove();
this is if accidentally they include a close button in their markup or if the attribute `render-on-open` is removed we don't need the close button anymore. But we also might want to have this kind of API for the component?

2024-02-20 12:09 UTC, akomiqaia commented on components/o3-tooltip/src/ts/tooltip.ts
> +	private getTargetNode() {
the ones that are not private are attributes of o3-tooltip or life cycle events. the only one we can make private is `render` function [552ecdd](https://github.com/Financial-Times/origami/pull/1429/commits/552ecddcc216189f4094af3a603c58d6169fad4e)

2024-02-20 12:09 UTC, akomiqaia commented on components/o3-tooltip/main.css
> +	margin-bottom: 8px;
[7a130fe](https://github.com/Financial-Times/origami/pull/1429/commits/7a130fecdfa2f0459ab0f1fe2c60047eef4c07d8)

2024-02-20 12:09 UTC, akomiqaia commented on components/o3-tooltip/main.css
> +	font-weight: inherit;
[0d3c990](https://github.com/Financial-Times/origami/pull/1429/commits/0d3c9905e7ee58dde5d754ace4f15b5d446f1bd8)

2024-02-20 12:11 UTC, akomiqaia commented on components/o3-tooltip/main.css
> +	font-size: 14px;
[7a130fe](https://github.com/Financial-Times/origami/pull/1429/commits/7a130fecdfa2f0459ab0f1fe2c60047eef4c07d8)

2024-02-20 15:44 UTC, akomiqaia commented on components/o3-tooltip/stories/core/tooltip.stories.tsx
> +	HoverToolTip as HoverToolTipStory,
how would that work on mobile phones though?

2024-02-26 17:39 UTC, notlee requested changes

2024-02-26 17:39 UTC, notlee commented on components/o3-tooltip/tsconfig.tsx.json
> +		"declarationDir": "./build/types",
I see an error related to this in o3-button, do we need to create a separate ticket?
```
tsconfig.tsx.json:5:3 - error TS5069: Option 'declarationDir' cannot be specified without specifying option 'declaration' or option 'composite'.
```

2024-02-26 17:39 UTC, notlee commented on components/o3-tooltip/main.css
> +	--_button-icon: var(--o3-icons-ft-icon-info);
The info button doesn't look good..? This is in Arc, a Chromium browser

<img width="243" alt="Screenshot 2024-02-26 at 17 13 04" src="https://github.com/Financial-Times/origami/assets/10405691/3dde6e30-ffb3-454e-ad73-7d04dacedfb5">

2024-02-26 17:39 UTC, notlee commented on .vscode/settings.json
> +  "typescript.tsdk": "node_modules/typescript/lib"
Does that mean we can delete this?

2024-02-26 17:39 UTC, notlee commented on apps/o3-storybook/.storybook/preview.ts
> +				tabWidth: 4,
Nice

2024-02-26 17:39 UTC, notlee commented on apps/o3-storybook/package.json
> -    "storybook-addon-designs": "^6.3.1",
Why have we removed this addon? Does the design tab still work?

2024-02-26 17:39 UTC, notlee commented on components/o3-tooltip/README.md
> +  </div>
We can simplify this interface for users, since we don't need this markup for the core experience.

1. We could create markup in JavaScript
2. Remove excess options, do we need `aria-label` and `title`? 

E.g.
```html
<o3-tooltip-toggle placement="bottom" class="o3-tooltip" targetLabel="Tooltip description">
    click the button to see the tooltip
</o3-tooltip-toggle>
```

Related, what does the core experience look like, when JavaScript isn't available or errors? Is this content hidden?

2024-02-26 17:39 UTC, notlee commented on components/o3-tooltip/README.md
> +  </div>
☝️ This applies to both types of tooltip

2024-02-26 17:39 UTC, notlee commented on components/o3-tooltip/src/ts/tooltip.ts
> +		this._isToggleTooltip = this.tagName === 'O3-TOOLTIP-TOGGLE';
Is the generic `tooltip.ts` the best place for toggle specific logic? The responsibilities of each class aren't clear

2024-02-27 09:57 UTC, akomiqaia commented on components/o3-tooltip/main.css
> +	--_button-icon: var(--o3-icons-ft-icon-info);
because there is no token for in Figma :D there is ticket in Jira for this.

2024-02-27 10:49 UTC, akomiqaia commented on apps/o3-storybook/package.json
> -    "storybook-addon-designs": "^6.3.1",
we already have an addon for designs  `@storybook/addon-designs": "^7.0.5"` which is their official suggestion.

2024-02-27 13:59 UTC, akomiqaia commented on components/o3-tooltip/tsconfig.tsx.json
> +		"declarationDir": "./build/types",
[d6e223e](https://github.com/Financial-Times/origami/pull/1429/commits/d6e223e1430e09e4b68939d3ee5691ce8b5a9dac)

2024-02-27 14:00 UTC, akomiqaia commented on components/o3-tooltip/src/ts/tooltip.ts
> +		this._isToggleTooltip = this.tagName === 'O3-TOOLTIP-TOGGLE';
check [891b479](https://github.com/Financial-Times/origami/pull/1429/commits/891b4795bf08be3c9bc44d73065a51316de5af0d)

2024-02-27 14:00 UTC, akomiqaia commented on components/o3-tooltip/README.md
> +  </div>
check [891b479](https://github.com/Financial-Times/origami/pull/1429/commits/891b4795bf08be3c9bc44d73065a51316de5af0d)

2024-02-28 10:56 UTC, akomiqaia commented
@notlee this adds professional theme and icon swapping for toggletip [df48ec6](https://github.com/Financial-Times/origami/pull/1429/commits/df48ec6831ca2a474940300dc986ba9546d81108)

2024-03-04 17:54 UTC, notlee reviewed
Getting closer, so...

1. I focused more on the README this time!
2. Some design issues with focus colour. Also the `x` icon still looks misaligned also.
3. What's going on with Sustainable Views?!

![Screenshot 2024-03-04 at 17 14 54](https://github.com/Financial-Times/origami/assets/10405691/495e7c54-a5bf-431c-9c26-674ffacba00f)
![Screenshot 2024-03-04 at 17 14 57](https://github.com/Financial-Times/origami/assets/10405691/6f584d17-c37f-44f5-91c8-87d98e8483a6)

2024-03-04 17:54 UTC, notlee commented on components/o3-tooltip/main.css
> +	background-color: var(--o3-color-palette-black-30);
We should raise the use of `black-30` with Deyan, as the contrast ratio on white is very low. We should be aiming for at least 3:1. `black-50` would achieve that I believe:
https://webaim.org/resources/contrastchecker/?fcolor=B3B3B3&bcolor=FFFFFF

2024-03-04 17:54 UTC, notlee commented on components/o3-tooltip/main.css
> +	padding: var(--padding-top) var(--padding-right) var(--padding-right)
Does `--padding-right` mean anything? It's applied to not right paddings.

2024-03-04 17:54 UTC, notlee commented on components/o3-tooltip/main.css
> +.o3-tooltip-wrapper .o3-tooltip-close::before {
Could these selectors align with the one below for focus states?

```suggestion
o3-tooltip-toggle button {
	all: unset; /* remove all default browser styles for buttons */
	width: var(--icon-button-size);
	height: var(--icon-button-size);
}

o3-tooltip-toggle button::before {
```

2024-03-04 17:54 UTC, notlee commented on components/o3-tooltip/main.css
> +	background-color: var(--o3-color-palette-black-30);
This applies to the close button too. Is there an opportunity to align their hover colours, which will also simplify your css?

2024-03-04 17:54 UTC, notlee commented on components/o3-tooltip/README.md
> +o3-tooltip is hosting two components: `o3-tooltip-onboarding` and `oe-tooltip-toggle`. Onboarding Tooltips help for a smoother introduction to new features or functionality. Toggletips are compact pi
```suggestion
o3-tooltip is hosting two components: `o3-tooltip-onboarding` and `o3-tooltip-toggle`. Onboarding Tooltips help for a smoother introduction to new features or functionality. Toggletips are compact pieces of information designed to offer additional insights when needed. See our [design guidelines for usage information and brand support](https://origami-for-everyone.ft.com).
```

(we can update the link when we have it)

2024-03-04 17:54 UTC, notlee commented on components/o3-tooltip/README.md
> +We provide custom elements `<o3-tooltip-onboarding>` and `<o3-tooltip-toggle>` to be used in your markup but we also equivalent provide [JSX components](#jsx) to be used in React.
This suggests we provide a React components – React users will still need to implement custom elements. How about?

```suggestion
We provide custom elements `<o3-tooltip-onboarding>` and `<o3-tooltip-toggle>`. React users may include these using our [JSX template](#jsx).
```

2024-03-04 17:54 UTC, notlee commented on components/o3-tooltip/README.md
> +`<o3-tooltip-onboarding>` is used to display a tooltip on a HTML target element that can have `aria-describedby` attribute. It is used to provide additional information about the target element and i
```suggestion
`<o3-tooltip-onboarding>` is used to display a tooltip on a HTML target element that can have an `aria-describedby` attribute. It is used to provide additional information about the target element and is shown immediately once the page is loaded. It can be only closed by clicking the close button.
```

2024-03-04 17:54 UTC, notlee commented on components/o3-tooltip/README.md
> +`o3-tooltip-toggle` does not have a close button and is used with info icon. It can be triggered by clicking on the info icon and will be removed from the DOM if user clicks outside of the tooltip, p
```suggestion
`o3-tooltip-toggle` does not have a close button and is used with an information icon. It can be triggered by clicking on the information icon and will be removed from the DOM if the user clicks outside of the tooltip, presses ESC, or clicks the info icon again.
```

2024-03-04 17:54 UTC, notlee commented on components/o3-tooltip/README.md
> +Bellow is a markup examples of how to use `<o3-tooltip-onboarding>` and `<o3-tooltip-toggle>` custom elements:
```suggestion
Below are examples of how to use `<o3-tooltip-onboarding>` and `<o3-tooltip-toggle>` custom elements:
```

2024-03-04 17:54 UTC, notlee commented on components/o3-tooltip/README.md
> +  class="o3-button o3-button--secondary o3-button--big demo-tooltip-target"
Instruction here on what attributes to change would be helpful. In addition, `o3-tooltip-content` could be renamed to more clearly indicate it's for demo purposes

2024-03-04 17:54 UTC, notlee commented on components/o3-tooltip/README.md
> +## Markup
I like that you introduce both tooltips initially, with a little overview. For the detail, splitting the 2 types of tooltips into sub-headings may make it easier to find and follow the correct instructions.

2024-03-04 17:54 UTC, notlee commented on components/o3-tooltip/README.md
> +```
- This will vary by project. It's good to flag that.
- Most of our users will be using PostCSS / Sass, so a more helpful example might use `@import`?
- There's some duplication here in copy and what you're showing, I believe we can reduce this sentence.

```suggestion
To style `o3-tooltip` import brand specific css, this varies depending on your project. For example:

```scss
@import '@financial-times/o3-tooltip/css/[your brand].css';
```
```

2024-03-04 17:54 UTC, notlee commented on components/o3-tooltip/README.md
> +`o3-tooltip` has a two JSX component exported that implement `<o3-tooltip-onboarding>` and `<o3-tooltip-toggle>` under the hood and export `TooltipOnboarding` and `TooltipToggle` respectively. To use
Again this suggests this is an alternative React implementation. I think it's better to avoid `implement` and `component`, in favour of `template` or `elements`:

```suggestion
`o3-tooltip` exports two JSX templates, `TooltipOnboarding` and `TooltipToggle` for each tooltip component. This means copy-pasting html can be avoided. For example:
```

2024-03-04 17:54 UTC, notlee commented on components/o3-tooltip/README.md
> +} from '@financial-times/o3-tooltip/jsx';
As a React user, do I need to take further steps? Perhaps not for this PR, but how do we make that clear?

2024-03-04 17:54 UTC, notlee commented on components/o3-tooltip/README.md
> +`TooltipOnboarding` component accept the following props:
```suggestion
The `TooltipOnboarding` JSX element accepts the following `props`:
```

2024-03-04 17:54 UTC, notlee commented on components/o3-tooltip/README.md
> +`ToggleTooltip` component accept the following props:
```suggestion
The `ToggleTooltip` JSX element accepts the following `props`:
```

2024-03-05 10:13 UTC, akomiqaia commented on components/o3-tooltip/README.md
> +} from '@financial-times/o3-tooltip/jsx';
do you have anything specific in mind here?

2024-03-05 10:17 UTC, frshwtr commented on components/o3-tooltip/.eslintignore
> +demos/local/**
We shouldn't need this now we don't have registry demos

2024-03-05 10:18 UTC, frshwtr commented on components/o3-tooltip/.eslintignore
> +demos/local/**
```suggestion
```

We shouldn't need this now we have decomissioned the registry

2024-03-05 10:18 UTC, frshwtr commented on components/o3-tooltip/.npmignore
> +demos/local/
```suggestion
```

2024-03-05 10:18 UTC, frshwtr commented on components/o3-tooltip/.stylelintignore
> +demos/local/**
```suggestion
```

2024-03-05 10:41 UTC, akomiqaia commented on components/o3-tooltip/main.css
> +	padding: var(--padding-top) var(--padding-right) var(--padding-right)
yeah here bottom padding is the same as left/right padding but only for onboarding tooltip with Title. do you think using just space values are much better?

2024-03-05 10:54 UTC, akomiqaia commented on components/o3-tooltip/main.css
> +	background-color: var(--o3-color-palette-black-30);
what do you mean by aligning hover colours? do you mean to have same color for focus and hover?

2024-03-05 13:28 UTC, notlee commented on components/o3-tooltip/README.md
> +} from '@financial-times/o3-tooltip/jsx';
Maybe nothing, since all props are strings. Would be a good one to work with Nikolay to try out in one of our production React environments.

- https://react.dev/reference/react-dom/components#custom-html-elements
- https://css-tricks.com/building-interoperable-web-components-react/

2024-03-05 13:30 UTC, notlee commented on components/o3-tooltip/main.css
> +	padding: var(--padding-top) var(--padding-right) var(--padding-right)
yeah, or renamed 👍 the current naming doesn't help understand what the relationship is between the places it's used

2024-03-07 10:41 UTC, notlee approved these changes
Let's go! 👏  We'll tidy up a little on the design / token side with a follow up release

2024-03-07 10:52 UTC, merged