fix:  do not affect nested expander elements
Financial-Times/origami pull request #1528
Opened 2024-04-03 14:51 UTC by juanSanchezAlcala

Expander was affecting to toggler buttons inside nested o-expander elements.
With this fix we exclude elements that are not nested

## Checklist before requesting a review
- [ ] I have applied `percy` label on my PR before merging and after review.
- [ ] If it is a new feature, I have added thorough tests.
- [ ] I have updated relevant docs.
- [ ] I have updated relevant env variables in Doppler.

2024-04-03 15:15 UTC, notlee commented on components/o-expander/stories/nested-expander.stories.tsx
> +	title: 'Components/o-expander/nested',
```suggestion
	title: 'Components/o-expander',
```

I don't think we need to group by `nested` here
![Screenshot 2024-04-03 at 16 14 10](https://github.com/Financial-Times/origami/assets/10405691/27b70c3c-9863-45f4-9378-a5c05429afb4)

2024-04-03 15:15 UTC, notlee requested changes
Looks reasonable! I'm happy to approve when tests are passing, are you happy to take a look at those?

2024-04-10 07:49 UTC, juanSanchezAlcala commented
> Looks reasonable! I'm happy to approve when tests are passing, are you happy to take a look at those?

Hi @notlee , maybe im wrong but i think [this test](https://github.com/Financial-Times/origami/blob/7391d124e3dd06385926451652e35fd989b50ce1/components/o-expander/test/custom.test.js#L83) isn't ok, since the title says that is testing shrinkTo with a number but the test sets "height" instead.

2024-04-10 08:36 UTC, juanSanchezAlcala commented
@notlee I've found the reason of the tests failing. In the tests some fixtures doesn't include data-o-component=o-expander . Im adding it on the code in case the expander element doesn't have it when initialising.

2024-04-10 10:01 UTC, notlee commented on components/o-expander/src/js/expander-utility.js
> +			item.closest('[data-o-component="o-expander"]') === this.oExpanderElement
Good find on the issue with the failing tests but I think this could lead to unexpected behaviour. Instead of setting `data-o-component` could you check for nested expanders by checking for the presence of the [initalized class](https://github.com/Financial-Times/origami/blob/e971320c09decb8e2d020f373320bca2f942394b/components/o-expander/src/js/expander.js#L29)?

The reason I think `data-o-component` could be a problem is because it's usually used to automatically initialise components by calling the `init` method, with no arguments, or by including the `o-autoinit` component. There's a small risk here that a project or its dependency tries to initialise all expanders after this constructor is called to manually initalise an expander without `data-o-component`, and therefore attempts to construct the same expander twice.

2024-04-10 12:27 UTC, juanSanchezAlcala commented on components/o-expander/src/js/expander-utility.js
> +			item.closest('[data-o-component="o-expander"]') === this.oExpanderElement
Use o-expander--intialized class is a problem because we get the toggle buttons on the initialisation and therefore that class is added at the end of the process , so we couldn't use it before.
In case some component has been initialised before it shouldn't be initialised twice checking if it has the initialized className. This is not implemented yet. If you think its ok that solution I'll add the needed code.

2024-04-10 12:35 UTC, juanSanchezAlcala commented
Not related with this PR but just in case its not right,
 Is this [objectAssign](https://github.com/Financial-Times/origami/blob/e971320c09decb8e2d020f373320bca2f942394b/components/o-expander/src/js/expander.js#L22) right ?  shouldn't be the other way around ?  
I mean the options passed to the object should override the default options, right ? 
At the moment the default is being assign to the options passed so it will override passed options

2024-04-10 13:39 UTC, notlee commented on components/o-expander/src/js/expander-utility.js
> +			item.closest('[data-o-component="o-expander"]') === this.oExpanderElement
Good point. I think checking for the "intialized" class class to avoid initialising twice works 👍 Our new components are standard Custom Elements, so this shouldn't be an issue going forward 🙌

2024-04-10 13:40 UTC, notlee commented
@juanSanchezAlcala yes that does look like it should be the other way around, weird it hasn't come up before, I guess no one is customising them? Wonder if we have tests against that?

2024-04-10 15:12 UTC, juanSanchezAlcala commented
> @juanSanchezAlcala yes that does look like it should be the other way around, weird it hasn't come up before, I guess no one is customising them? Wonder if we have tests against that?

If i switch the objectAssing arguments and run the test they passed correctly, though i wouldn't change this without a breaking change, since if there is some code passing options to oExpander it will change the logic and potentially could change the behaviour and cause an issue.

2024-04-10 15:14 UTC, juanSanchezAlcala commented on components/o-expander/src/js/expander-utility.js
> +			item.closest('[data-o-component="o-expander"]') === this.oExpanderElement
I have changed a bit the way to check if its initialised. 
And also i set init method to return always the same instance even it was already initialised, take a look and let me know if you think its ok

2024-04-12 08:52 UTC, notlee approved these changes

2024-04-12 08:52 UTC, merged