chore: release main
Financial-Times/origami pull request #1574
Opened 2024-04-17 12:42 UTC by origamiserviceuser

:robot: I have created a release *beep* *boop*
---

<details><summary>o3-typography: 0.1.1</summary>

## [0.1.1](https://github.com/Financial-Times/origami/compare/o3-typography-v0.1.0...o3-typography-v0.1.1) (2024-04-17)

### Bug Fixes

* Use o3-foundation instead of deprecated o3-web-token.
* use correct export approach ([#1577](https://github.com/Financial-Times/origami/issues/1577)) ([3ccc6bc](https://github.com/Financial-Times/origami/commit/3ccc6bc59a2e01fde40e576418bda3ffbaa174ba))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

2024-04-17 12:59 UTC, frshwtr approved these changes

2024-04-17 13:22 UTC, notlee requested changes
We can improve the changelog here

2024-04-17 13:22 UTC, notlee commented on components/o3-typography/CHANGELOG.md
> +* peer dependency on correct foundation library ([#1573](https://github.com/Financial-Times/origami/issues/1573)) ([e90eaac](https://github.com/Financial-Times/origami/commit/e90eaac202c5c1033d1fe137
```suggestion
* Use o3-foundation instead of deprecated o3-web-token.
```

2024-04-18 07:22 UTC, notlee approved these changes

2024-04-18 07:23 UTC, merged

2024-04-18 07:23 UTC, origamiserviceuser commented
:robot: Release is at https://github.com/Financial-Times/origami/releases/tag/o3-typography-v0.1.1 :sunflower: