Or 665 editorial components
Financial-Times/origami pull request #1633
Opened 2024-05-07 14:45 UTC by akomiqaia

## Describe your changes
Adds: 
- body elements
- details

and bigger components such as:

-  typography headline with underline
- quote
- big number
- byline

2024-05-07 15:58 UTC, frshwtr commented on components/o3-editorial-typography/main.css
> +@import './layer.css';
What's the purpose behind the layer css?

2024-05-07 16:01 UTC, frshwtr commented on components/o3-editorial-typography/src/tsx/body.tsx
> +	if (theme == 'inverse') {
This check is repeated across all three components that are currently being put into o3. We should look to reduce the duplication of this.

There's an implementation in [o3-typography](https://github.com/Financial-Times/origami/blob/main/components/o3-typography/src/tsx/getStyleAttributes.tsx). Maybe we can move the function to a more generic space for all o3 components to use.

2024-05-07 16:06 UTC, frshwtr commented on components/o3-editorial-typography/stories/story-templates.tsx
> +type BodyStory = Omit<StoryObj, 'args'> & {
`Omit<StoryObj, 'args'>` can be assigned to a type alias to reduce the repetition if needed.

```tsx
type StoryObjNoArgs = Omit<StoryObj, 'args'>
```

2024-05-08 09:23 UTC, akomiqaia commented on components/o3-editorial-typography/main.css
> +@import './layer.css';
nothing much except setting text colours for typography classes and inversing it. and it is imported before others so later timestamp colours can override default text/inverse-text colours. Also it reduces code and instead of repeating the same pattern in all files we can just put it in one file. We could just write that code in any other file and it will still work but it might not be as clean and readable for other contributors. Open to other suggestions as well

2024-05-09 10:49 UTC, notlee requested changes

2024-05-09 10:49 UTC, notlee commented on components/o3-editorial-typography/details.css
> +blockquote.o3-editorial-typography-quote {
Is the distinction between `.o3-editorial-typography-quote` and `blockquote.o3-editorial-typography-quote` intentional?

2024-05-09 10:49 UTC, notlee commented on components/o3-editorial-typography/details.css
> +.o3-editorial-typography-quote {
This is _very_ different from our current editorial quote. Are these intentional design changes or a mistake?

Left: o2; Right: o3
<img width="1186" alt="Screenshot 2024-05-09 at 11 38 01" src="https://github.com/Financial-Times/origami/assets/10405691/75bb933c-d6b9-4d24-a2cc-d5083151f3b0">


https://o2.origami.ft.com/?path=/story/o2-core_components-o-quote--editorial-quote

2024-05-09 10:49 UTC, notlee commented on components/o3-editorial-typography/details.css
> +.o3-editorial-typography-quote-caption {
Following BEM these should use underscores to indicate they are an element of quote, which shouldn't be used independently

`o3-editorial-typography-quote__author`
`o3-editorial-typography-quote__caption`

2024-05-09 10:49 UTC, notlee commented on components/o3-editorial-typography/details.css
> +.o3-editorial-typography-big-number-title {
Same here `.o3-editorial-typography-big-number__title`

2024-05-09 10:49 UTC, notlee commented on components/o3-editorial-typography/details.css
> +.o3-editorial-typography-big-number-content {
`o3-editorial-typography-big-number__content` 

etc...

2024-05-09 10:49 UTC, notlee commented on components/o3-editorial-typography/layer.css
> +[data-o3-theme='inverse'] [class^='o3-editorial-typography-'],
Funky! Love it!

2024-05-09 10:49 UTC, notlee commented on components/o3-editorial-typography/details.css
> +.o3-editorial-typography-byline-author {
Our current [byline author](https://o2-core.origami.ft.com/?path=/story/components-o-editorial-typography-byline-with-timestamp--byline-with-timestamp&globals=backgrounds:!undefined) often links to the author's page. I believe it may not always be a link though.

When it is a link, how should it be styled? Is it changing from o2?

2024-05-09 10:49 UTC, notlee commented on components/o3-editorial-typography/stories/core/detail.stories.tsx
> +import type {Meta} from '@storybook/react';
Detail feels like a quite random grouping, it doesn't make it very easy to find the right story. 

1. It seems to allow quote author / caption use outside of the quote component, which I don't think we want.
2. Perhaps speak to Mary about how we want to present the other "details". Maybe one story each. Maybe we can group some, like if it's the most common use we may want to present a byline Story.

<img width="299" alt="Screenshot 2024-05-09 at 11 47 07" src="https://github.com/Financial-Times/origami/assets/10405691/8a7ae4d5-9f49-4d93-a4f1-487e10f508fe">
these.

2024-05-09 10:49 UTC, notlee commented on components/o3-editorial-typography/stories/core/body.stories.tsx
> +import {Body as BodyTsx} from '../../src/tsx/index';
Are you adding support for SV? One for Mary and Deyan.

2024-05-09 11:08 UTC, akomiqaia commented on components/o3-editorial-typography/details.css
> +blockquote.o3-editorial-typography-quote {
not really. I think `blockquote` can be removed here

2024-05-09 11:13 UTC, akomiqaia commented on components/o3-editorial-typography/stories/core/body.stories.tsx
> +import {Body as BodyTsx} from '../../src/tsx/index';
I will add support but we don't have Figma files in SV or Core. I am developing just Core and then copy over story files.

2024-05-09 11:22 UTC, notlee commented on components/o3-editorial-typography/details.css
> +.o3-editorial-typography-quote {
👍 on the icon issue, I always forget that

2024-05-09 11:22 UTC, akomiqaia commented on components/o3-editorial-typography/details.css
> +.o3-editorial-typography-byline-author {
well, byline is only a wrapper here and users can pass custom markup and styling of that should be up to users. We could include more in the readme maybe?

2024-05-09 11:23 UTC, akomiqaia commented on components/o3-editorial-typography/stories/core/detail.stories.tsx
> +import type {Meta} from '@storybook/react';
yeah this is a good suggestion. Will talk to Marry and see what she thinks

2024-05-09 11:26 UTC, notlee commented on components/o3-editorial-typography/details.css
> +.o3-editorial-typography-quote {
@akomiqaia There are 2 quote styles here

**Pull Quote**

This _is not_ currently in Origami. It's defined [custom in cp-content-pipeline](https://github.com/Financial-Times/cp-content-pipeline/blob/97ffc6689b6d8d78635728f77e3a35c0598689b4/packages/styles/scss/_pullquotes.scss#L1). Do we want to add to Origami now? Probably not a bad idea! 
<img width="438" alt="Screenshot 2024-05-09 at 12 23 28" src="https://github.com/Financial-Times/origami/assets/10405691/48de3ed6-af55-42dd-a7e0-175582467de7">

**Block Quote**

This _is_ in Origami already, and is [imported by cp-content-pipeline](https://github.com/Financial-Times/cp-content-pipeline/blob/97ffc6689b6d8d78635728f77e3a35c0598689b4/packages/styles/scss/_blockquotes.scss#L1). Here's an [example on a dummy ft article](https://www.ft.com/kitchenus-sinkus-articlus).

<img width="645" alt="Screenshot 2024-05-09 at 12 25 30" src="https://github.com/Financial-Times/origami/assets/10405691/4380b580-8b5d-4581-af89-bced7aa4ebcb">

We should port this over.

____

Perhaps Mary isn't aware. Are you happy to raise with her to decide whether to add both pull and block quotes?

2024-05-09 13:46 UTC, notlee commented on components/o3-editorial-typography/details.css
> +.o3-editorial-typography-byline-author {
Yes please 👍 We should document what customisations we allow and include an API to do that without overriding CSS. E.g. we give people a public CSS Custom Property to set rather than them setting random styles

2024-05-09 13:47 UTC, notlee commented on components/o3-editorial-typography/stories/core/body.stories.tsx
> +import {Body as BodyTsx} from '../../src/tsx/index';
👍 Do you know if Mary has worked with Deyan or Marin to design SV alternatives?

2024-05-09 14:56 UTC, akomiqaia commented on components/o3-editorial-typography/details.css
> +.o3-editorial-typography-quote {
Mary will update the Figma file and will support both types of quote components.

2024-05-09 14:57 UTC, akomiqaia commented on components/o3-editorial-typography/details.css
> +.o3-editorial-typography-byline-author {
Okay, I will think about this. This sounds like a good idea.

2024-05-14 08:59 UTC, frshwtr commented on components/o3-editorial-typography/main.css
> +@import './layer.css';
I think the separation is fine :) But there might be a name for the file that helps communicate it's purpose. Something like `theme.css` or `theming.css`

2024-05-14 13:49 UTC, notlee commented on components/o3-editorial-typography/README.md
Actually... article body is supposed to be responsive, similar to the headline, there shouldn't be a large and small variant.

2024-05-14 13:49 UTC, notlee commented on components/o3-editorial-typography/details.css
> +	color: var(--o3-editorial-typography-byline-author-hover-color);
We need an inverse variant on hover here!

![Screenshot 2024-05-14 at 14 03 54](https://github.com/Financial-Times/origami/assets/10405691/13b678c5-2bdc-4075-b57e-2604a56b8526)

2024-05-14 13:49 UTC, notlee commented on components/o3-editorial-typography/stories/story-templates.tsx
> +				<div>
A `div` inside a `p` tag isn't valid html – I'm seeing errors in the console from the html tab plugin

2024-05-14 13:49 UTC, notlee commented on components/o3-editorial-typography/details.css
> +.o3-editorial-typography-quote__block {
The blockquote is inline with content and should use Georgia.
Are the design changes to the author/caption intentional? 

![Screenshot 2024-05-14 at 14 48 02](https://github.com/Financial-Times/origami/assets/10405691/60696051-418b-4c76-9b5f-3977aeb1c243)

2024-05-14 14:23 UTC, akomiqaia commented on components/o3-editorial-typography/README.md
so it depends on a view-port? I think I asked Mary about this but that was not the case. Might be wrong but can double check

2024-05-14 14:24 UTC, akomiqaia commented on components/o3-editorial-typography/list.css
> +	counter-reset: item;
what are they? unordered and ordered sounds like list modifiers :D

2024-05-14 14:29 UTC, akomiqaia commented on components/o3-editorial-typography/details.css
> +.o3-editorial-typography-quote__block {
I am waiting for Figma designs and tokens for the quote component and updates can happen afterwards. Do you have an actual example of a block quote on ft pages? The quotes I checked were all in metric font on ft.com

2024-05-21 13:48 UTC, notlee approved these changes
✨

2024-05-21 13:50 UTC, merged