chore: changed sv editorial typography tokens to desired values; adde…
Financial-Times/origami pull request #1686
Opened 2024-06-04 09:34 UTC by itsdeyan

…d financier-text to the sv usecase typography tokens

## Describe your changes

## Issue ticket number and link

## Link to Figma designs

## Checklist before requesting a review

- [ ] I have applied `percy` label for o-[COMPONENT] or `chromatic` label for o3-[COMPONENT] on my PR before merging and after review. Find more details in [CONTRIBUTING.md](https://github.com/Financial-Times/origami/blob/main/CONTRIBUTING.md#pull-requests-and-visual-regression-tests)
- [ ] If it is a new feature, I have added thorough tests.
- [ ] I have updated relevant docs.
- [ ] I have updated relevant env variables in Doppler.

2024-06-04 09:57 UTC, frshwtr commented on apps/dictionary/tokens/sustainable-views/components/o3-editorial-typography.json
> -      "headline-large-l": {
Why were these removed?

2024-06-04 10:09 UTC, itsdeyan commented
they were obsolete for SV that's why I deleted them

2024-06-05 09:31 UTC, akomiqaia approved these changes
This looks good to me but before merging it we need to generate tokens and also create demos for professional.

2024-06-05 09:32 UTC, akomiqaia requested changes
gonna block this since I accidentally approved it

2024-06-07 10:54 UTC, itsdeyan commented on components/o3-foundation/src/css/tokens/sustainable-views/_variables.css
> +  --o3-font-weight-thinnest: 1;
The only way to make Financier Text VF appear properly in Figma was to set the variable font weight to the value of 1. That's why I created this, please let me know if it's wrong and what's the right way to do it, thanks.

2024-06-07 14:59 UTC, frshwtr commented on components/o3-editorial-typography/src/tsx/detail.tsx
> +			{...attributes}>
The `href` attribute will still be present when `HtmlElement` is a `span`. A cleaner approach would be to use the ternary to change what element is returned.
```suggestion
return href ? <a href className="o3-editorial-typography-topic-tag">{children}</a> : <span className="o3-editorial-typography-topic-tag">{children}</span>
```

2024-06-07 15:12 UTC, notlee requested changes
Missing tokens for pull quotes and block quotes. Does SV support these? If not, they should be removed from Storybook.
<img width="899" alt="Screenshot 2024-06-07 at 16 09 10" src="https://github.com/Financial-Times/origami/assets/10405691/86651ca3-59fc-46f5-a25a-f80953230d61">

No paper background on SV stories! 🙏 
<img width="888" alt="Screenshot 2024-06-07 at 16 09 34" src="https://github.com/Financial-Times/origami/assets/10405691/2a1a9335-130e-4d76-8582-95b241bce293">

The `inverse` theme is broken in places. Deyan said we don't need to support the inverse theme for SV. Can we remove it entirely for SV, including tokens and the SB control?
<img width="801" alt="Screenshot 2024-06-07 at 16 10 00" src="https://github.com/Financial-Times/origami/assets/10405691/fbf765f4-f801-4f15-8bb1-ca17868d8a39">

2024-06-11 14:27 UTC, notlee approved these changes

2024-06-11 14:54 UTC, merged