feat: remove current edition and change cross style
Financial-Times/origami pull request #1725
Opened 2024-06-18 08:43 UTC by danieleruiz

## Describe your changes
Due to the redesign initiative of the search bar navigation, the current edition will become part of the "edition-switcher" component of [dotcom-page-kit](https://github.com/Financial-Times/dotcom-page-kit). The logo should be centered, and the close cross should be moved to the left.

## Issue ticket number and link
https://financialtimes.atlassian.net/browse/CON-3426
## Link to Figma designs
https://www.figma.com/design/L6qyUFPPLRmf59OxTkz2VJ/Semantic-Search?node-id=279-91827&m=dev
## Checklist before requesting a review

- [ ] I have applied `percy` label for o-[COMPONENT] or `chromatic` label for o3-[COMPONENT] on my PR before merging and after review. Find more details in [CONTRIBUTING.md](https://github.com/Financial-Times/origami/blob/main/CONTRIBUTING.md#pull-requests-and-visual-regression-tests)

2024-06-19 14:39 UTC, frshwtr commented on components/o-header/test/search.test.js
>  							<label class="o-header__visually-hidden" for="o-header-search-term-js">Search the <abbr title="Financial Times">FT</abbr></label>
The text here should be updated to match the placeholder text

2024-07-02 09:12 UTC, danieleruiz commented on components/o-header/test/search.test.js
>  							<label class="o-header__visually-hidden" for="o-header-search-term-js">Search the <abbr title="Financial Times">FT</abbr></label>
updated

2024-07-02 10:39 UTC, notlee commented on components/o-header/src/scss/features/_drawer.scss
>  	.o-header__drawer-search-term {
This is an improvement to the submit button but it lacks hover and active states. Could we replace this with [o-buttons](https://o2-core.origami.ft.com/?path=/story/components-o-buttons--big-button&args=icon:search;type:primary;iconOnly:!true&globals=backgrounds:!undefined)? The [oButtonsContent](http://localhost:6006/?path=/docs/components-o-buttons-sassdoc--docs&globals=backgrounds:!undefined#obuttonscontent) mixin allows us to apply button styles to a custom class. 

Something like

```scss
.o-header__drawer-search-submit {
    @include oButtonsContent($opts: (
        'type': 'primary',
         'icon-only': true,
        'icon': 'search'
    ));
}
```

2024-07-02 10:39 UTC, notlee commented on components/o-header/src/scss/features/_drawer.scss
>  		// be a breaking change, this colour could go in o-colors as a usecase
Should we reconsider the form dependency? The design team are working on some fundamental design language changes for later this year which will impact forms – think shape and colour. By adding forms as a dependency we:
1. Can be more confident of consistency today.
1. Know where forms are used, and can check changes work in this context.
1. Design changes will flow apply via the dependency, without us needing to remember to update multiple components

2024-07-02 10:39 UTC, notlee commented on components/o-header/src/scss/features/_drawer.scss
> +		height: 16px;
Is this height intended to create margin? Using `margin` would be more explicit and therefore easier to read.

2024-07-02 10:39 UTC, notlee commented on components/o-header/src/scss/features/_drawer.scss
> +		background-color: #333333;
This grey is not part of our colour palette, could we use a [black tint](https://o2-core.origami.ft.com/?path=/story/components-o-colors-color-mixer--color-mixer&globals=backgrounds:!undefined) instead?

2024-07-02 10:39 UTC, notlee commented on components/o-header/src/scss/features/_drawer.scss
> +		margin-right: 10px;
Please stick to our [standard spacing scale](https://o2-core.origami.ft.com/?path=/docs/components-o-spacing-readme--docs&globals=backgrounds:!undefined). This could be `oSpacingByName('s1')` (12px). 

(o-header is an old component and is full of negative examples)

2024-07-02 10:54 UTC, danieleruiz commented on components/o-header/src/scss/features/_drawer.scss
>  	.o-header__drawer-search-term {
done

2024-07-02 11:08 UTC, danieleruiz commented on components/o-header/src/scss/features/_drawer.scss
> +		background-color: #333333;
done

2024-07-02 11:14 UTC, danieleruiz commented on components/o-header/src/scss/features/_drawer.scss
> +		margin-right: 10px;
done

2024-07-02 11:19 UTC, danieleruiz commented on components/o-header/src/scss/features/_drawer.scss
> +		height: 16px;
this line is to make the divider line visible:
<img width="237" alt="Captura de pantalla 2024-07-02 a las 13 17 37" src="https://github.com/Financial-Times/origami/assets/98393608/9f7f632d-471c-4609-a736-1fc06f9a9e31">

2024-07-02 13:50 UTC, notlee commented on components/o-header/src/scss/features/_drawer.scss
>  		// be a breaking change, this colour could go in o-colors as a usecase
What styles would you need to override? Perhaps the design is off

2024-07-02 13:55 UTC, notlee commented on components/o-header/src/scss/features/_drawer.scss
> +		background-size: contain;
We should be able to remove `background-size: contain;` here by setting the button size `'size': 'big'` and removing the styles for `.o-header__drawer-search-submit` above, then we'll be relying on standardised button styles without custom css

2024-07-02 16:36 UTC, danieleruiz commented on components/o-header/src/scss/features/_drawer.scss
> +		background-size: contain;
done! thank you!

2024-07-03 08:46 UTC, danieleruiz commented on components/o-header/src/scss/features/_drawer.scss
>  		// be a breaking change, this colour could go in o-colors as a usecase
o-forms had some styles that only applies if are inside a specific form element so if i include only the input clases somethimes is not 100% the same, anyways im using a common mixin for the button and changing the height of the  input. so i dont think that worth it to include a dependency and new clases with need parents etc

2024-07-03 15:56 UTC, notlee requested changes
The vertical spacing on desktop search looks a little off, there is more space above than below:

![Screenshot 2024-07-03 at 16 35 58](https://github.com/Financial-Times/origami/assets/10405691/4331607d-4933-4333-9e62-2758ed5233a9)

2024-07-03 15:56 UTC, notlee commented on components/o-header/src/scss/features/_drawer.scss
>  	.o-header__drawer-tools-logo {
I believe this class is redundant now, can we safely delete it?

2024-07-03 15:56 UTC, notlee commented on components/o-header/src/scss/features/_drawer.scss
> +			order: 2;
Replying on `order` here means the [tab order](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-order.html) is a little surprising. Could we reorder the markup instead of relying on CSS `order` here?

2024-07-03 15:56 UTC, notlee commented on components/o-header/src/scss/features/_drawer.scss
> +		margin-left: -10px;
This negative margin feels a bit hacky and difficult to maintain. Could we align the padding of the parent elements instead? `o-header__drawer-tools` `o-header__drawer-search` `o-header__drawer-actions` should all have the same horizontal padding.

2024-07-03 15:56 UTC, notlee commented on components/o-header/src/scss/features/_drawer.scss
> +				color: var(--Black-Tints-Black-60, #66605C);
This custom property doesn't exist.

```suggestion
				color: oColorsByName('black-60');
```

2024-07-03 20:14 UTC, danieleruiz commented on components/o-header/src/scss/features/_drawer.scss
>  	.o-header__drawer-tools-logo {
removed

2024-07-04 07:26 UTC, danieleruiz commented on components/o-header/src/scss/features/_drawer.scss
> +		margin-left: -10px;
the paddings are the same, the problem here is that the background of "x" close button have like 10px of margin centered on a svg file so to make it be aligned i had to add this negative margin

2024-07-04 12:03 UTC, notlee commented on components/o-header/src/scss/features/_drawer.scss
> +		padding: ($_o-header-drawer-padding-y * 2.5) 0 0 $_o-header-drawer-padding-x;
Is the top padding too high here? The close button should align with where the burger menu was
<img width="361" alt="Screenshot 2024-07-04 at 13 03 23" src="https://github.com/Financial-Times/origami/assets/10405691/64c82a1f-d076-4023-bc28-83b7a93a0610">

2024-07-04 14:20 UTC, danieleruiz commented on components/o-header/src/scss/features/_drawer.scss
> +		padding: ($_o-header-drawer-padding-y * 2.5) 0 0 $_o-header-drawer-padding-x;
changed !

2024-07-05 08:47 UTC, danieleruiz commented
> The vertical spacing on desktop search looks a little off, there is more space above than below:
> 
> ![Screenshot 2024-07-03 at 16 35 58](https://private-user-images.githubusercontent.com/10405691/345506407-4331607d-4933-4333-9e62-2758ed5233a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDYzMjAsIm5iZiI6MTcyMDEwNjAyMCwicGF0aCI6Ii8xMDQwNTY5MS8zNDU1MDY0MDctNDMzMTYwN2QtNDkzMy00MzMzLTllNjItMjc1OGVkNTIzM2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDE1MTM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NmYzZTljM2UzM2I4N2RiZTQ1ZDM4MzhjOThlMmNiMjUzOGE0NGU5ZWFjY2Q0Yzk5MmM4MjYxODNiY2ZmYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O-vmwEnnY0_znXpfUUj7SKTErAwdhBqwu7Gbm1GKlC8)

fixed it

2024-07-05 10:38 UTC, notlee approved these changes

2024-07-05 10:40 UTC, merged