docs: align editorial typography docs with figma
Financial-Times/origami pull request #1736
Opened 2024-07-04 13:57 UTC by frshwtr

## Describe your changes

## Issue ticket number and link

## Link to Figma designs

## Checklist before requesting a review

- [ ] I have applied `percy` label for o-[COMPONENT] or `chromatic` label for o3-[COMPONENT] on my PR before merging and after review. Find more details in [CONTRIBUTING.md](https://github.com/Financial-Times/origami/blob/main/CONTRIBUTING.md#pull-requests-and-visual-regression-tests)
- [ ] If it is a new feature, I have added thorough tests.
- [ ] I have updated relevant docs.
- [ ] I have updated relevant env variables in Doppler.

2024-07-05 10:57 UTC, akomiqaia commented on apps/for-everyone-website/src/components/editorial-typography/BodyStyles.astro
> -				<FigmaSbLinks figma={figmaBody} storybook={sbBody} />
Are links not useful here?

2024-07-05 10:58 UTC, akomiqaia commented on apps/for-everyone-website/src/components/editorial-typography/BodyStyles.astro
> +	tablet, and esktop.
```suggestion
	tablet, and desktop.
```

2024-07-05 11:00 UTC, akomiqaia approved these changes
LGTM just one typo and a question.

2024-07-05 15:37 UTC, frshwtr commented on apps/for-everyone-website/src/components/editorial-typography/BodyStyles.astro
> -				<FigmaSbLinks figma={figmaBody} storybook={sbBody} />
@akomiqaia This was following what was in [Figma](https://www.figma.com/design/y25ZjT1MqqHbNXNXsm8DET/Documentation-Content-Template?node-id=139-548&t=6hp2KFL1EchgbpZh-0)

2024-07-08 12:59 UTC, notlee requested changes
Thanks for picking up this ticket in my absence, but it's not what Mary and I had intended. It's a faithful implementation of what's in Figma, but it is intended only to convey content – it's not a website design.

- We aimed to replace tables with Previews to reduce repetition and allow engineers to copy HTML/JSX. For example we intended to present the three bylines elements as one in a Preview.
- This hard codes values (e.g. body is Georgia / regular / scale 2).  It's inaccurate, as it's not true for all brands. It is hard to maintain. We should use tokens to document values but this is also quite expensive to maintain. Me and Mary discussed costs and benefits, and agreed to remove the values here for now.
- Accessibility notes: This is superfluous and should be deleted. Someone would have to try hard for lists not to be navigable by keyboard.

Let me know if you'd like to discuss this. Since Mary and I previously went over the content changes, I'd be happy to pick this back up now I'm back if you like

2024-08-08 10:46 UTC, frshwtr commented on apps/for-everyone-website/src/components/editorial-typography/BodyStyles.astro
> +<p>Use for body text, paragraphs and lists. This is responsive.</p>
I cannot approve (as discussed on standup) as i opened this. My review:

* `BodyStyles.astro` still exists, can the previews still be moved to mdx?

2024-08-09 12:14 UTC, merged