feat: introduce o3 grid CSS custom properties
Financial-Times/origami pull request #1764
Opened 2024-07-30 10:11 UTC by frshwtr

## Describe your changes

## Issue ticket number and link

## Link to Figma designs

## Checklist before requesting a review

- [ ] I have applied `percy` label for o-[COMPONENT] or `chromatic` label for o3-[COMPONENT] on my PR before merging and after review. Find more details in [CONTRIBUTING.md](https://github.com/Financial-Times/origami/blob/main/CONTRIBUTING.md#pull-requests-and-visual-regression-tests)
- [ ] If it is a new feature, I have added thorough tests.
- [ ] I have updated relevant docs.
- [ ] I have updated relevant env variables in Doppler.

2024-07-30 11:02 UTC, notlee commented on components/o3-foundation/grid.css
> +		--o3-foundation-grid-margin: var(--o3-spacing-2xl);
Looks like a good start, nice use of custom properties here.

This doesn't yet capture [contained width behaviour](https://origami-beta.ft.com/guides/grid/#contained-width-behaviour). In the past we've provided a CSS class to set a max width, and put the grid within it. However we know from our design guidelines that content can break out of this container. Our old approach forced users to layout with negative margins, which are somewhat hacky and difficult to work with. 

I wonder if instead we're able to use the grid template to contain those 12 columns, and have 2 extra columns (1 either side) to represent the infinite margins on desktop.

2024-07-30 15:26 UTC, frshwtr commented on components/o3-editorial-typography/stories/core/grid.stories.tsx
> +import type {Meta} from '@storybook/react';
This isn't needed for the grid. It can be removed or potentially tidied up to demo grids if need be.

2024-07-30 15:27 UTC, frshwtr commented on components/o3-editorial-typography/stories/core/grid.css
> +
Likewise, this isn't necessary.

2024-08-08 10:25 UTC, frshwtr commented on components/o3-foundation/stories/grid.tsx
> +		const handleResize = () => {
When it comes to users of o3 grid, are they going to need to do something similar to this to handle content flow on resizes?

2024-08-08 15:51 UTC, notlee requested changes

2024-08-08 15:51 UTC, notlee commented on components/o3-foundation/grid.css
> +		--o3-grid-area: 'spread-left content-start . . . . . . content-end spread-right';
There are some issues to work out here still.

On wider viewports the content area is larger than it should be by a few px.

<img width="1437" alt="Screenshot 2024-08-08 at 16 49 36" src="https://github.com/user-attachments/assets/fff131d8-152e-413e-98f8-8b2886073c9c">

And on a tablet-ish viewport we end up with 8 columns between content grid lines rather than 12
<img width="977" alt="Screenshot 2024-08-08 at 16 49 59" src="https://github.com/user-attachments/assets/ff08d2be-2c6b-4ec5-bf36-fbf56ba2343c">

2024-08-08 15:54 UTC, notlee commented
There's no JSX so let's delete this page? It doesn't add anything the story doesn't provide.

<img width="1544" alt="Screenshot 2024-08-08 at 16 53 30" src="https://github.com/user-attachments/assets/b02bb345-b8b1-4622-8702-b54f460fbaf2">

We should improve documentation with detailed technical guides in the README and a summary with link on the website.

2024-08-08 16:23 UTC, akomiqaia commented on components/o3-foundation/grid.css
> +		--o3-grid-area: 'spread-left content-start . . . . . . content-end spread-right';
we have 8 columns on that screen size. https://origami-for-everyone.ft.com/guides/grid/ we get 12 on 980px.

2024-08-08 16:26 UTC, akomiqaia commented on components/o3-foundation/grid.css
> +		--o3-grid-area: 'spread-left content-start . . . . . . content-end spread-right';
And there is some rounding issue because at 1220px (code media query is 1268px because of margins) screen we set the width of the column using calc and it's not quite divisible perfectly.

2024-08-08 16:27 UTC, akomiqaia commented
> ae01cbe

[ae01cbe](https://github.com/Financial-Times/origami/pull/1764/commits/ae01cbe327dd658dd494226e0291083aa796310b)

2024-08-09 10:20 UTC, notlee commented on components/o3-foundation/grid.css
> +		--o3-grid-area: 'spread-left content-start . . . . . . content-end spread-right';
Ah sorry, I didn't realise we have 8 as an intermediate number of columns 👍

2024-08-09 10:46 UTC, notlee commented on components/o3-foundation/grid.css
> +		--o3-grid-area: 'spread-left content-start . . . . . . content-end spread-right';
I've asked Mary whether there was a strong rationale for the 1220px container. I'd prefer to have an exact container width and equal columns when the contained width is reached (but it doesn't matter too much, I don't think). We might want to choose a different container size. Definitely for a separate PR if so though

_____

Current o-grid:
1180px container with 12 columns, 11 gutters, 20px gutter: (1180 - (11 * 20)) / 12 = 76px columns

New o3 guidelines don't divide well at contained width :grimacing:
1220px container with 12 columns, 11 gutters: (1220 - (11 * 24)) / 12 = 79.66666666666666px columns

1200px or 1260px work better with the same gutter:
1200px container with 12 columns, 11 gutters: (1200 - (11 * 24)) / 12 = 76px columns
1260px container with 12 columns, 11 gutters: (1260 - (11 * 24)) / 12 = 83px columns

2024-08-09 10:49 UTC, notlee commented
Thanks @akomiqaia! Could you also add to the foundations readme to document the grid including the named grid lines? 

Suggestion: Might bleed start / end be easier to remember? Since it aligns with the wording we use in design guidelines and content start/end?

```diff
-bleed-start content-start . . . . . . content-end bleed-end
+spread-left content-start . . . . . . content-end spread-right
```

2024-08-09 10:54 UTC, notlee commented on components/o3-foundation/grid.css
> +		--column-width: calc((1220px - 11 * var(--o3-grid-gap)) / 12);
💡It might be handy to have a public `--o3-grid-column-width` available at all viewports? It would allow us to align elements to grid columns when they're nested in other elements and can't be positioned with the actual CSS Grid. For example Deyan suggested form elements should be x columns wide by default

```
input {
    min-width: calc(4 * var(--o3-grid-column-width));
}
```

Thoughts?

2024-08-09 10:57 UTC, notlee commented on components/o3-foundation/grid.css
> +	gap: var(--o3-grid-gap);
We don't want to force this gap between rows 
```suggestion
	column-gap: var(--o3-grid-gap);
```

2024-08-12 08:42 UTC, akomiqaia commented on components/o3-foundation/grid.css
> +		--column-width: calc((1220px - 11 * var(--o3-grid-gap)) / 12);
This is a good thought. We should consider making a ticket for it.

2024-08-12 13:38 UTC, notlee commented on components/o3-foundation/README.md
> +o3-foundation provides CSS Custom Properties for grid that you can set on your class:
Consider the order of this by the message you want to convey, since it's likely the reader will be glancing through rather than reading from top to bottom.

It's impossible to use the grid effectively without understand the design guidelines. A brief introduction and link to the design guidelines would be a better way to open: https://origami-beta.ft.com/guides/grid/

If `o3-grid` is the convenient option, perhaps share that first and the detail of custom properties later if needed.

2024-08-12 13:38 UTC, notlee commented on components/o3-foundation/README.md
> +- The 12-Column Grid Structure: The `o3-grid` system is built on a 12-column grid structure. These 12 columns are utilized within the `content-start` and `content-end` boundaries.
This isn't true on mobile and tablet like viewports. We could perhaps say something like "the number of columns is variable according to viewport size, see design guidelines for details (link)". This highlights important information to know without repeating details which could get outdated more easily

2024-08-12 13:38 UTC, notlee commented on components/o3-foundation/README.md
> +- Bleed Columns for Extended Layouts: `bleed-start` & `bleed-end`: These special columns extend beyond the 12-column grid, reaching the edges of the viewport. This allows you to create "full-bleed" l
👍 Sounds good. Could even link to the relevant design guidelines here

2024-08-12 14:01 UTC, notlee approved these changes

2024-08-12 14:08 UTC, merged