Am/o header
Financial-Times/origami pull request #1777
Opened 2024-08-14 11:25 UTC by metart43

## Describe your changes

## Issue ticket number and link

## Link to Figma designs

## Checklist before requesting a review

- [ ] I have applied `percy` label for o-[COMPONENT] or `chromatic` label for o3-[COMPONENT] on my PR before merging and after review. Find more details in [CONTRIBUTING.md](https://github.com/Financial-Times/origami/blob/main/CONTRIBUTING.md#pull-requests-and-visual-regression-tests)
- [ ] If it is a new feature, I have added thorough tests.
- [ ] I have updated relevant docs.
- [ ] I have updated relevant env variables in Doppler.

2024-08-14 12:44 UTC, danieleruiz commented on components/o-header/src/tsx/search.tsx
> -						aria-controls="o-header-search-js"
this was previously diffferent with the js prefix, is that for any reason or is ok to change that without js prefix?

2024-08-14 12:45 UTC, danieleruiz commented on components/o-header/src/tsx/sticky.tsx
> +	const inputFieldId = 'o-header-search-term-js';
here we maintain the js prefix? can we remove as we did above?

2024-08-14 14:22 UTC, danieleruiz approved these changes

2024-08-15 13:46 UTC, frshwtr approved these changes

2024-08-15 14:22 UTC, notlee requested changes
Hey, 

I haven't had time to do a proper review but I can see this isn't quite ready for release yet. For example, markup changes are classed as a breaking change so we need to ensure this is a major release and has a migration guide. 

As I'm off tomorrow I've written up a [Jira Ticket](https://financialtimes.atlassian.net/browse/OR-829) to capture some things the Origami team should pay some closer attention to on review

2024-08-15 14:36 UTC, metart43 commented
@notlee 

> - The search bar can display at least twice, in the main nav and the sticky nav. Ensure they both work and the correct input/controls/labels are associated.

**Search bar can be displayed three times.** Drawer, sticky and main nav. 

In production label and controls currently are not properly associated. See this [commit](https://github.com/Financial-Times/origami/pull/1777/commits/c4bd6f25b85ef374ae3dbc5a07b7713e81ea0ee3) for the reference. If you inspect the main input field and it's label you will spot they reference different IDs.

I can write up a migration guide, highlighting changes described in this PR. The main change related to the `type="search"` and introduction of a `z-index`. Everything else is trivial.

2024-08-19 10:07 UTC, frshwtr commented
hi @metart43, which demo did you use for the screenshots? I can't replicate this locally.

2024-08-19 10:10 UTC, metart43 commented
@frshwtr you should be able to start up the storybook and go to http://localhost:6006/?path=/story/components-o-header--header-primary&globals=backgrounds:!undefined

2024-08-19 14:23 UTC, frshwtr commented
It's quite hard to see but it seems the button is about 1px taller than the search bar, is that intentional?
<img width="540" alt="image" src="https://github.com/user-attachments/assets/ac75f30c-1c90-452d-82b8-ae7a52525b54">

2024-08-20 09:08 UTC, metart43 commented
@notlee thanks for advising to write up a migration guide. I have pushed a commit to do so https://github.com/Financial-Times/origami/pull/1777/commits/d533203fc35fde6721f32aebbea7567e6624cd71

2024-08-21 10:02 UTC, frshwtr commented on components/o-header/MIGRATION.md
> +## Migrating from v13 to v14
This guide is useful in providing updates on the changes to TSX users. o-header also supports HTML and CSS users. Please could you add some details on how I would upgrade my code using this approach? 

`Migrating from v11 to v12`  in this file has some examples of the things to mention. Mostly an example of the overall HTML to use (from the storybook link) and details on what individual sections can be removed/added/updated.

2024-08-21 10:10 UTC, frshwtr commented
> @frshwtr I am not sure if you are QAing the changes I've pushed. Th screenshot you've shared doesn't look right. I can see that the button on your screenshot looks different to what I have locally
> 
> Please, see the dimension of the search bar and the button was (42px):
> 
> <img alt="Screenshot 2024-08-20 at 09 58 24" width="604" src="https://private-user-images.githubusercontent.com/27081787/359410358-bc2ccd91-3163-4e40-a7a2-fceb74daec8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDczNjQsIm5iZiI6MTcyNDE0NzA2NCwicGF0aCI6Ii8yNzA4MTc4Ny8zNTk0MTAzNTgtYmMyY2NkOTEtMzE2My00ZTQwLWE3YTItZmNlYjc0ZGFlYzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA5NDQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ODk2Yjk2OGJlNzI0MWQ0NzMyMWQxZmIxYzViNTRkZWEzMTkzN2RhYzE5ZWExYjEzOTc3NzExOGE3MTI2ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F8sF7Hoi-aEHs0nfPS4_2ENQ6ly278QWpR386t2R1yA"> <img alt="Screenshot 2024-08-20 at 09 58 14" width="456" src="https://private-user-images.githubusercontent.com/27081787/359410365-e1413561-3049-471e-8dc1-406160d7f055.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDczNjQsIm5iZiI6MTcyNDE0NzA2NCwicGF0aCI6Ii8yNzA4MTc4Ny8zNTk0MTAzNjUtZTE0MTM1NjEtMzA0OS00NzFlLThkYzEtNDA2MTYwZDdmMDU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA5NDQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YjA4N2Y1NjM3Zjc5NGU2Yzc3ZWJmMjM4MGI1NzU2MzA4NjZlZWZiNzYzNThjYzQ4MDExMGJmNzg2M2U0ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O4zS7zYk5gTpHbxC8xm8KbRu3FBaAMWpY__YUX3FDEs">
> I have pushed a commit to reduce the icon height, the bar height should be `40` [034a682](https://github.com/Financial-Times/origami/commit/034a6829c648503a5c8968150bfd6221eed3e378)

This looks good now, thanks.

2024-08-21 13:24 UTC, metart43 commented on components/o-header/MIGRATION.md
> +## Migrating from v13 to v14
Thanks for pointing this. I've addressed in https://github.com/Financial-Times/origami/pull/1777/commits/a3573423d733a7001af4af43bc27fcb928429915

2024-08-21 15:06 UTC, merged