feat: introduce o-grid to o-private-foundation
Financial-Times/origami pull request #1875
Opened 2024-11-14 14:43 UTC by frshwtr

## Describe your changes

## Issue ticket number and link

## Link to Figma designs

## Checklist before requesting a review

- [ ] I have applied `percy` label for o-[COMPONENT] or `chromatic` label for o3-[COMPONENT] on my PR before merging and after review. Find more details in [CONTRIBUTING.md](https://github.com/Financial-Times/origami/blob/main/CONTRIBUTING.md#pull-requests-and-visual-regression-tests)
- [ ] If it is a new feature, I have added thorough tests.
- [ ] I have updated relevant docs.
- [ ] I have updated relevant env variables in Doppler.

2024-11-14 14:55 UTC, frshwtr commented
Ensure o-grid is removed or moved to `devDependencies` so that demos can still use it if needed.

2024-11-19 09:42 UTC, frshwtr commented on components/o-teaser/demos/src/demo.scss
> +	@include oPrivateGridColspan((default: 12, M: 6, XL: 4));
I have intentionally changed this demo as it is depending on `main.scss`

2024-11-21 13:06 UTC, notlee requested changes
Looks like a good start, I think we can delete a lot more Sass. Comments on what we can delete aren't exhaustive:

2024-11-21 13:06 UTC, notlee commented on components/o-private-foundation/src/scss/o-grid/_variables.scss
> +$o-private-grid-is-silent: true !default;
This isn't used and can be deleted

2024-11-21 13:06 UTC, notlee commented on components/o-private-foundation/src/scss/o-grid/main.scss
> +@mixin oPrivateGrid($opts: (
`oGrid` doesn't appear to be used outside of component demos except for in o-header-services:

```scss
@include oGrid((
		'surface': ('current-layout'),
	));
```

Can we replace that with `@include oPrivateGridSurfaceCurrentLayout;` and delete `oPrivateGrid`? This should in turn allow us to delete a bunch more variables, functions, and mixins.

2024-11-25 14:47 UTC, notlee commented on components/o-private-foundation/src/scss/o-grid/_variables.scss
> +$o-pf-grid-layouts: (
I see you've mapped `$_o-pf-grid-mode` to `$o-grid-mode` 👍 `$o-pf-grid-layouts` will also need to map to the public o-grid variable to avoid breaking changes. We should review the remaining public grid variables and decide whether they should be mapped.
https://github.com/Financial-Times/ft-app/blob/92b36af986a39ce01ae31834822b74f9cc1df13f/lib/css/_origami-override-vars.scss#L3

2024-11-25 15:10 UTC, frshwtr commented on components/o-private-foundation/src/scss/o-grid/_variables.scss
> +$o-pf-grid-layouts: (
Would assigning the variable twice overcome this need?

```sass
$o-pf-grid-fixed-layout: $o-grid-fixed-layout;
$o-pf-grid-fixed-layout: 'S' !default;
```

2024-11-26 11:02 UTC, notlee approved these changes

2024-11-26 17:02 UTC, notlee reviewed
I see the build is failing, you'll need to use global-variable-exists:
https://sass-lang.com/documentation/modules/meta/#global-variable-exists

2024-11-27 15:38 UTC, merged