chore: Stop being an esm module
Financial-Times/origami pull request #332
Opened 2021-09-30 17:00 UTC by chee

Instead we'll use .mjs files. Storybook didn't like it when
its main file was in a type: module repo

2021-09-30 17:02 UTC, chee commented on package.json
> +    "test": "node ./scripts/test.mjs",
```suggestion
	"install": "cp hooks/* .git/hooks && cd tools/origami-build-tools && npm ci",
	"test": "node ./scripts/test.mjs"
```

2021-09-30 17:05 UTC, chee commented on scripts/check-next-version.mjs
> +} from "./lib/getChangedPackages.mjs"
```suggestion
} from "./lib/get-changed-packages.mjs"
```

2021-10-01 12:42 UTC, notlee requested changes

2021-10-01 12:42 UTC, notlee commented on .github/workflows/sync-repo-labels.yml
> -      - uses: Financial-Times/origami-labels@v1
Looks good except was deleting this intentional?

2021-10-01 12:44 UTC, chee commented on .github/workflows/sync-repo-labels.yml
> -      - uses: Financial-Times/origami-labels@v1
yes, our labeling strategy for this repo doesn't include `origami-labels`

2021-10-01 12:47 UTC, chee commented
another strategy would be to move the storybook stuff into a subdirectory with its own package json

2021-10-01 17:38 UTC, closed without merging