Remove icon for external links which o-typography provides in a mixin
Financial-Times/origami pull request #636
Opened 2022-02-11 11:01 UTC by JakeChampion

During the origami accessibility audit it was discovered that the icon
makes some people think the link will open in a new window which
is not what the icon is meant to mean.

After looking at what other sites do such as gov.uk - we found that they removed their external link icon ([designnotes.blog.gov.uk/2016/11/28/removing-the-external-link-icon-from-gov-uk](https://designnotes.blog.gov.uk/2016/11/28/removing-the-external-link-icon-from-gov-uk/))
One of the reasons why was "The icon is not widely recognised and is often confused with the ‘opens in a new window’ icon"

To remove this confusion for our users, we are going to remove the icon from our external link styling as well

2022-02-11 12:31 UTC, JakeChampion commented on components/o-typography/src/scss/use-cases/_general.scss
> +	}
👋 @chee and @notlee

The approach I've currently gone with is to remove the styling for external links, it looks like external link styling only added the icon.

I've also added a warn/deprecation message, instead of removing the $external parameter - I'm thinking this approach would make this a non-breaking change, do you think that is correct and the approach we should take here?

2022-02-11 15:36 UTC, JakeChampion commented on components/o-typography/src/scss/use-cases/_general.scss
> +	}
Once we are happy with an approach, I will re-add the percy configs and have them all run :D

2022-02-14 14:03 UTC, JakeChampion commented on components/o-typography/src/scss/use-cases/_general.scss
> +	}
I've re-added the percy configs now 👍

2022-02-14 14:42 UTC, notlee requested changes
I think the o-typography Stories might also need updating

2022-02-14 14:42 UTC, notlee commented on components/o-cookie-message/src/js/cookie-message.js
> +	We use <a href="http://help.ft.com/help/legal-privacy/cookies/" class="o-cookie-message__link" target="_blank" rel="noopener">cookies <span class="o-cookie-message__visually-hidden">(opens in a new
I think the open in the new tab message will be read twice because `o-cookie-message__link` uses the mixin `oTypographyLink` and has `target="_blank"`. Probably want this in the following PR instead? If we do decide to move away from the pseudo element approach.
https://github.com/Financial-Times/origami/pull/637

2022-02-14 14:42 UTC, notlee commented on components/o-typography/src/scss/use-cases/_general.scss
> +		@warn 'The $external parameter for oTypographyLink is deprecated. ' +
Nice, I like that you included why in the warning. I thought some explicit instruction might be helpful too
```suggestion
		@warn 'The $external parameter for oTypographyLink is deprecated. ' +
		'Remove the $external argument from the oTypographyLink call.' +
```

2022-02-14 15:11 UTC, JakeChampion commented on components/o-cookie-message/src/js/cookie-message.js
> +	We use <a href="http://help.ft.com/help/legal-privacy/cookies/" class="o-cookie-message__link" target="_blank" rel="noopener">cookies <span class="o-cookie-message__visually-hidden">(opens in a new
```suggestion
	We use <a href="http://help.ft.com/help/legal-privacy/cookies/" class="o-cookie-message__link" target="_blank" rel="noopener">cookies</a> for a number of reasons, such as keeping FT Sites reliable and secure, personalising content and ads, providing social media features and to analyse how our Sites are used.
```

2022-02-14 15:18 UTC, JakeChampion commented on components/o-typography/src/tsx/typography.tsx
> -	if(external) {
@notlee - I updated the stories to remove `external` and remove the external-link story -- let me know if this is what you want and if so, I will readd the percy configs

2022-02-14 16:06 UTC, notlee commented on apps/website/_tutorials/build-service.md
> +<aside>We'll be providing code snippets for you to follow, but you can also have a look at the <a href="https://codepen.io/ft-origami/full/ejLNNL" rel="noreferrer noopener" target="_blank" class="o-t
sorry I missed this, the same applies with adding "opens a new tab" to these inks too:
https://github.com/Financial-Times/origami/pull/636#discussion_r805907256

2022-02-14 16:07 UTC, notlee commented on components/o-cookie-message/test/helpers/fixtures.js
> +				We use <a href="http://help.ft.com/help/legal-privacy/cookies/" class="o-cookie-message__link" target="_blank" rel="noopener">cookies <span class="o-cookie-message__visually-hidden">(opens in a n
Looks lie these fixtures need updating too re https://github.com/Financial-Times/origami/pull/636#discussion_r805907256

2022-02-14 16:08 UTC, JakeChampion commented on components/o-cookie-message/test/helpers/fixtures.js
> +				We use <a href="http://help.ft.com/help/legal-privacy/cookies/" class="o-cookie-message__link" target="_blank" rel="noopener">cookies <span class="o-cookie-message__visually-hidden">(opens in a n
```suggestion
				We use <a href="http://help.ft.com/help/legal-privacy/cookies/" class="o-cookie-message__link" target="_blank" rel="noopener">cookies</a>
```

2022-02-14 16:08 UTC, JakeChampion commented on components/o-cookie-message/test/helpers/fixtures.js
> +				We use <a href="http://help.ft.com/help/legal-privacy/cookies/" class="o-cookie-message__link" target="_blank" rel="noopener">cookies <span class="o-cookie-message__visually-hidden">(opens in a n
```suggestion
				We use <a href="http://help.ft.com/help/legal-privacy/cookies/" class="o-cookie-message__link" target="_blank" rel="noopener">cookies</a>
```

2022-02-14 16:09 UTC, notlee commented on components/o-cookie-message/test/helpers/fixtures.js
> +				We use <a href="http://help.ft.com/help/legal-privacy/cookies/" class="o-cookie-message__link" target="_blank" rel="noopener">cookies <span class="o-cookie-message__visually-hidden">(opens in a n
there are a few 😅 a find and replace should get 'em

2022-02-14 16:10 UTC, JakeChampion commented on apps/website/_posts/2019-01-30-newsletter.md
> +We launched v3 of the Polyfill service, which was outlined in a separate launch email. This release includes better polyfills, a faster service, and a more maintainable codebase. There's a <a href="h
```suggestion
We launched v3 of the Polyfill service, which was outlined in a separate launch email. This release includes better polyfills, a faster service, and a more maintainable codebase. There's a <a >migration guide here</a>, or check out the live service at <a href="https://polyfill.io/v3/">polyfill.io</a>.
```

2022-02-14 16:11 UTC, JakeChampion commented on apps/website/_posts/2019-02-28-newsletter.md
> +  - MINOR: <a href="https://registry.origami.ft.com/components/o-grid@4.5.1">o-grid v4.5.1</a> enables named exports as well as the default object <a href="https://github.com/Financial-Times/o-grid/i
```suggestion
  - MINOR: <a href="https://registry.origami.ft.com/components/o-grid@4.5.1">o-grid v4.5.1</a> enables named exports as well as the default object <a href="https://github.com/Financial-Times/o-grid/issues/177">(see issue)</a>. Thanks Chee Rabbits!
```

2022-02-14 16:12 UTC, JakeChampion commented on apps/website/_posts/2019-02-28-newsletter.md
> +  - MINOR: <a href="https://github.com/Financial-Times/polyfill-library/releases"x to support online IDEs such as <a href="https://repl.it/".com/Financial-Times/polyfill-library/releases">multiple ot
```suggestion
  - MINOR: <a href="https://github.com/Financial-Times/polyfill-library/releases">polyfill-library v3.30.1</a> now minifies feature detection JS and a fix to support online IDEs such as <a href="https://repl.it/">repl.it</a> (credit to Kate Beard, who is currently bootcamping with Origami). Plus <a href="https://github.com/Financial-Times/polyfill-library/releases" class="o-typography-link--external">multiple other minor releases</a> this month have updated and added new polyfills (Jake Chamion 💪). Including, but not limited to:
```

2022-02-14 16:14 UTC, JakeChampion commented on apps/website/_tutorials/build-service.md
> +<aside>We'll be providing code snippets for you to follow, but you can also have a look at the <a href="https://codepen.io/ft-origami/full/ejLNNL" rel="noreferrer noopener" target="_blank" class="o-t
```suggestion
<aside>We'll be providing code snippets for you to follow, but you can also have a look at the <a href="https://codepen.io/ft-origami/full/ejLNNL" rel="noreferrer noopener" target="_blank" class="o-typography-link">result of the tutorial</a>.</aside>
```

2022-02-14 16:15 UTC, JakeChampion commented on apps/website/_tutorials/build-service.md
> +<aside><a href="https://codepen.io/ft-origami/pen/wxEBda" rel="noreferrer noopener" target="_blank" class="o-typography-link">Show me the CodePen (opens a new tab)</a></aside>
```suggestion
<aside><a href="https://codepen.io/ft-origami/pen/wxEBda" rel="noreferrer noopener" target="_blank" class="o-typography-link">Show me the CodePen</a></aside>
```

2022-02-14 16:15 UTC, JakeChampion commented on apps/website/_tutorials/build-service.md
> +<aside><a href="https://codepen.io/ft-origami/pen/LBJErq" rel="noreferrer noopener" target="_blank" class="o-typography-link">Show me the CodePen (opens a new tab)</a></aside>
```suggestion
<aside><a href="https://codepen.io/ft-origami/pen/LBJErq" rel="noreferrer noopener" target="_blank" class="o-typography-link">Show me the CodePen</a></aside>
```

2022-02-14 16:15 UTC, JakeChampion commented on apps/website/_tutorials/build-service.md
> +<aside><a href="https://codepen.io/ft-origami/pen/VENXyQ" rel="noreferrer noopener" target="_blank" class="o-typography-link">Show me the CodePen (opens a new tab)</a></aside>
```suggestion
<aside><a href="https://codepen.io/ft-origami/pen/VENXyQ" rel="noreferrer noopener" target="_blank" class="o-typography-link">Show me the CodePen</a></aside>
```

2022-02-14 16:16 UTC, JakeChampion commented on apps/website/_tutorials/new-component/create-a-new-component-part-1.md
> +If you have any questions please contact the Origami team to help make this tutorial better &#x1F603;. You can find the team on Slack in <a href="https://financialtimes.slack.com/messages/{{site.data
```suggestion
If you have any questions please contact the Origami team to help make this tutorial better &#x1F603;. You can find the team on Slack in <a href="https://financialtimes.slack.com/messages/{{site.data.contact.slack}}" target="_blank">#{{site.data.contact.slack}}</a>.
```

2022-02-14 16:16 UTC, JakeChampion commented on apps/website/_tutorials/new-component/create-a-new-component-part-8.md
> +If you have any questions, bug reports, or feature requests please contact the Origami team &#x1F603;. You can find the team on Slack in <a href="https://financialtimes.slack.com/messages/{{site.data
```suggestion
If you have any questions, bug reports, or feature requests please contact the Origami team &#x1F603;. You can find the team on Slack in <a href="https://financialtimes.slack.com/messages/{{site.data.contact.slack}}" target="_blank">#{{site.data.contact.slack}}</a>.
```

2022-02-16 13:15 UTC, notlee approved these changes
approved! with percy changes reverted 😅

2022-02-16 15:00 UTC, merged