Add stories for o-icons demos
Financial-Times/origami pull request #732
Opened 2022-05-17 10:16 UTC by ivomurrell

All the different icons are selectable from a drop-down menu instead of all being rendered at once. The list of options is derived from the `fticons` imageset.

Custom icons are a little weird as they're just a span calling with a CSS class set, and the real work happens in the Sass. It doesn't seem worth creating a TSX component for that. It's also a bit harder to see what's going on under the hood compared to other components as we surface the generated HTML in a Storybook addon, but not the CSS. You can still easily inspect the code in your browser though, of course.

2022-05-17 11:17 UTC, chee commented on components/o-icons/src/tsx/icon.tsx
> +}
not for this PR but we could generate this `interface` as part of a build step

2022-05-17 14:19 UTC, chee commented on components/o-icons/src/tsx/icon.tsx
> +	icon: IconName;
```suggestion
	icon: IconName;
```

2022-05-17 14:20 UTC, chee commented on components/o-icons/src/scss/_icon-list.scss
> +	written-text
👁️👀👁️

2022-05-18 09:42 UTC, notlee commented
Just done a little rebase there.

2022-05-18 09:44 UTC, notlee requested changes
Sorry almost merged but I see chee noticed something happened to the eye icons. When they're restored I think this is good to go :) 

https://github.com/Financial-Times/origami/pull/732/files#r874880314

2022-05-18 09:46 UTC, notlee commented on components/o-icons/stories/icons.scss
> +.demo-icon-custom-color {
Please delete the custom colour story! Sorry I didn't think to mention. We decided to only show demos in storybook that are actually approved by design and part of the FT design system, which means we don't show icons with random "this is possible" colours

2022-05-27 14:11 UTC, ivomurrell commented on components/o-icons/src/scss/_icon-list.scss
> +	written-text
This script uses the imageset from https://github.com/Financial-Times/fticons (which supposedly replaces `o-icons`...? huh) which doesn't include the newly added 👁️ icons. Maybe we should move away from that data source for the script in the future?

2022-05-30 08:05 UTC, notlee commented on components/o-icons/scripts/build-icon-list.cjs
> +	writeTsInterface(images, `${__dirname}/../src/tsx/data.ts`);
🙌

2022-05-30 08:13 UTC, merged