O messages tsx
Financial-Times/origami pull request #748
Opened 2022-06-08 11:48 UTC by akomiqaia

2022-06-08 11:49 UTC, akomiqaia commented on components/o-message/src/tsx/message.tsx
> +			wrapper={children => <div className="demo-inner-message" style={{margin: "auto", maxWidth: "400px"}}>{children}</div>}>
This feels like a hack for displaying component. Maybe you have an idea why `demo-innner-message` did not apply styling?

2022-06-08 11:50 UTC, akomiqaia commented on components/o-message/stories/message.stories.tsx
> +		guidelines: {
where do i find this for this component?

2022-06-08 11:53 UTC, akomiqaia commented on components/o-message/stories/message.stories.tsx
> +	}, [args.showCloseButton])
I copied this code from `Banner.tsx` and it works. I get the idea but `.destroy()` seems to be unnecessary. since message does not have function that destroys it. do we know what happens if we don't use `useEffect()` and just initialise javascript?

2022-06-08 12:00 UTC, chee commented on components/o-message/stories/message.stories.tsx
> +		guidelines: {
don't worry about this right now, you can just set this to the empty object

2022-06-08 12:02 UTC, chee commented on components/o-message/src/tsx/message.tsx
> +			wrapper={children => <div className="demo-inner-message" style={{margin: "auto", maxWidth: "400px"}}>{children}</div>}>
these .tsx templates are for public consumption. if there is something we want specific to the demos, then that should be defined in ◌́message.stories.tsx◌́ and not be part of the component itself.

nothing with a demo class should exist in the exported component.

the reason this is not setting the styles is that class is defined here: https://github.com/Financial-Times/origami/blob/main/components/o-message/demos/src/demo.scss

and that file is not imported.

2022-06-08 12:03 UTC, chee commented on components/o-message/src/tsx/message.tsx
> +	hasInnerLayout=false,
```suggestion
	inner=false,
```

let's make this the simpler `inner` to match the modifier class name

2022-06-08 12:05 UTC, chee commented on components/o-message/src/tsx/message.tsx
> +			condition={hasInnerLayout}
i don't think we need to do this, setting `inner` should only add the `o-message--inner` modifier to the `o-message` element

2022-06-08 12:05 UTC, chee commented on components/o-message/src/tsx/message.tsx
> +}
```suggestion
type MessageAction = {
	label: string;
	url: string;
	openInNewWindow?: boolean
}
```

i think we've used the name `label` in other components for this

2022-06-08 12:06 UTC, chee commented on components/o-message/src/tsx/message.tsx
> +	hightLight?: string;
```suggestion
	highlight?: string;
```

2022-06-08 12:07 UTC, chee commented on components/o-message/src/tsx/message.tsx
> +}
```suggestion
type MessageAction = {
	text: string;
	url: string;
	openInNewWindow?: boolean
}
```

actually, let's make it `text` here to match [the javascript api of this component ](https://registry.origami.ft.com/components/o-message@5.2.2/readme?brand=core#options)

2022-06-08 12:10 UTC, chee commented on components/o-message/src/tsx/message.tsx
> +			wrapper={children => <div className="demo-inner-message" style={{margin: "auto", maxWidth: "400px"}}>{children}</div>}>
i answered this elsewhere, but it's because that class is defined in the component's demo.scss

2022-06-08 12:11 UTC, chee commented on components/o-message/stories/message.stories.tsx
> +	}, [args.showCloseButton])
```suggestion
	useEffect(() => void javascript.init(), [])
```

this is probably fine

2022-06-08 12:16 UTC, chee commented on components/o-message/src/tsx/message.tsx
> +			wrapper={children => <div className="demo-inner-message" style={{margin: "auto", maxWidth: "400px"}}>{children}</div>}>
we also want to avoid importing that file. this inner-message wrapper business should probably be moved to the stories file, and if you find you need css for the container you can add it in the sass file imported by the story

2022-06-08 14:20 UTC, akomiqaia commented
@chee your review was very useful and updated code according to your recommendations.

2022-06-14 15:05 UTC, notlee commented
FYI I just rebased on main so we can build the internal brand storybook for this branch

2022-06-14 15:34 UTC, notlee requested changes
Nice work on this @akomiqaia! 👏 It's looking great but I noticed it's possible to create messages which aren't supported with a combination of brand/type/layout/state, we need to work on the Storys and typescript interface to prevent that. o-message is a more complicated one to start on than I realised!

2022-06-14 15:34 UTC, notlee commented on components/o-message/src/tsx/message.tsx
> +	parentElement?: string;
I think we can delete these 2 options? It looks like they are not needed for the template and are only relevant when creating a message with the JavaScript API, without existing DOM elements.

2022-06-14 15:34 UTC, notlee commented on components/o-message/src/tsx/message.tsx
> +	state:
Not all states are supported by all brands and we should reflect that in the Storybook / typescript definitions. For example `warning` states are only supported for the internal brand and visually breaks when selected using a core brand storybook build.

There's a table in the readme with details of which brands support which message types/layouts/states.
https://registry.origami.ft.com/components/o-message@5.2.2/readme?brand=internal#message-types

I've never had to solve this one before so don't have an approach to recommend! But I see Ivo has given it some thought in [his draft PR for o-labels](https://github.com/Financial-Times/origami/pull/746/files#diff-aec22530edf46a8b8cda01fdcdf1c6e1ff297ad05d794b2ee8b4951b1a4c5713R3) :) Maybe have a look at that and see what you think.
![Screenshot 2022-06-14 at 16 17 56](https://user-images.githubusercontent.com/10405691/173615228-a6697c9d-dabc-49ad-bb97-316db27faaf6.png)

2022-06-14 15:34 UTC, notlee commented on components/o-message/src/tsx/message.tsx
> +	inner?: boolean;
Similar to the brand issue mentioned before, not all message types support `inner`:
https://registry.origami.ft.com/components/o-message@5.2.2/readme?brand=internal#message-types

Is it possible to make this prop depend on the value in another prop? If not maybe we need a typescript type for each message type e.g `ActionMessageProps` which extends a base type e.g. `MessageProps`?

2022-06-24 10:31 UTC, notlee reviewed
Nice this is great! Again nice spot on `includeStories`. I've picked up on 2 minor things which would be nice to address before we release if you don't mind? But this is good to go! 😄

2022-06-24 10:31 UTC, notlee commented on components/o-message/src/tsx/message.tsx
> +					<div className="o-message__actions">
Both actions are optional, so we should remove the whole of `<div className="o-message__actions"> ... </div>` if no actions are provided.

2022-06-24 10:31 UTC, notlee commented on components/o-message/stories/message-alert.stories.tsx
> +	<div style={{margin: 'auto', maxWidth: '400px'}}>{Story()}</div>
![Screenshot 2022-06-24 at 11 26 06](https://user-images.githubusercontent.com/10405691/175516631-5ee3fcf9-9c9b-41cd-ad93-316ff3db82dd.png)

This demo markup is shown in the html tab, I expect we'll end up with users copying this and thinking all inner messages should have a 400px max width 😅 

- It would be great if we could find a way to exclude decorators from the html tab. Or failing...
- We might consider adding a demo class like `demo-inner-message-container` instead of inline styles, with the css in `stories/message.scss`. As least when users copy and paste this the class is obviously only for demo purposes and the demo styles won't apply in their project

2022-06-24 10:40 UTC, akomiqaia commented on components/o-message/stories/message-alert.stories.tsx
> +	<div style={{margin: 'auto', maxWidth: '400px'}}>{Story()}</div>
I had this class before and removed it. But you are right I did not really think about others copping it with max-width. I will update the code again. Can investigate if we can exclude the decorators from html markup. But this HTML render is plugin written by origami right?

2022-06-24 10:48 UTC, notlee commented on components/o-message/stories/message-alert.stories.tsx
> +	<div style={{margin: 'auto', maxWidth: '400px'}}>{Story()}</div>
Yeah that's right, see `apps/storybook/addons/html/index.js`

2022-06-24 14:36 UTC, merged