Create component
Financial-Times/origami pull request #795
Opened 2022-08-23 14:54 UTC by akomiqaia

2022-08-24 11:19 UTC, notlee reviewed
This is shaping up really nicely, it's going to be so good to release.

I found a few issues / improvements we could make whilst manually testing as if I were a user. It looks like a long list but don't worry, there's nothing major! 😄 I also code reviewed the tests but have left the rest of the code review for later.

- After generating the component there's a "here's what it looks like" but I don't see anything?
![Screenshot 2022-08-24 at 10 20 06](https://user-images.githubusercontent.com/10405691/186403648-914aceb1-660a-4015-94cf-d95055ad81b4.png)

- After generating a component I can't start working on it before running `npm install @financial-times/o-component`. Should create-component run the npm install command automatically?

- Similarly I needed to run `npm run regenerate`. Should probably be automated with `create-component`.

- There's an issue with the JS import `./src/js/component-name.js` vs `./src/js/o-component-name.js`.

- Storybook Sass [should include o-fonts and o-normalise](https://github.com/Financial-Times/origami/blob/e7f42fb43ba3fcfb0502aa92cd971c0aa090fa51/components/o-typography/stories/typography.scss#L1-L4) – we don't do a good job of documenting for users that we expect them to include those in projects too

- We can remove the pally demo, we run automated accessibility checks on all demos now.

- There are some eslint and typescript warnings in the generated JS. Would be a good time to improve that now before people start creating components with the same warnings :)

- Brand selection is optional but we should require that supported brands are specified for new components. 

- `undefined` output on cancel

![Screenshot 2022-08-24 at 10 59 03](https://user-images.githubusercontent.com/10405691/186405380-e2659dd4-e80b-4218-85b7-2a1944467502.png)

- Demo and Storybook Sass files are generated when `scss: false`. A demo JS file is  also generated when `javascript: false`. Let's update the tests to capture that 🙌

2022-08-24 11:19 UTC, notlee commented on tools/create-component/__tests__/prompts.test.ts
> +			done()
Does this cause an error? Looks like `done` shouldn't be called when returning a promise
https://mochajs.org/#working-with-promises

2022-08-24 13:21 UTC, akomiqaia commented on .prettierignore
> +!tools/create-component
yes but. `.prettierignore` is in the root folder and since `tools/` was there it does not care what is inside the `tools/` but if we `tools/*` and then exclude `create-component` prettier starts working again. For some reason I can not format components either in our repo.

2022-08-24 14:20 UTC, akomiqaia commented on .prettierignore
> +!tools/create-component
[a57ef68](https://github.com/Financial-Times/origami/pull/795/commits/a57ef687907fef1e1cdf0786808d4ac5c3678a07)

2022-08-24 14:20 UTC, akomiqaia commented on package.json
> +	"private": true,
[a57ef68](https://github.com/Financial-Times/origami/pull/795/commits/a57ef687907fef1e1cdf0786808d4ac5c3678a07) this commit should help with this.

2022-08-24 14:31 UTC, notlee commented on .prettierignore
> +!tools/create-component
Ohh! That makes sense. Same issue, we're ignoring everything under `components/`. [Let's remove the ignores and run prettier on all the things](https://github.com/Financial-Times/origami/pull/798)?

We should also add `tools/create-component/.prettierrc.toml` though to support VS Code workspace.

2022-08-24 14:35 UTC, akomiqaia commented on tools/create-component/__tests__/prompts.test.ts
> +			done()
unfortunately it will fail. you are write about the `done()` not being necessary but I will need to rewrite test s from 
```js
it('should accept a correctly formatted name', async done => {
	const sendKeystrokes = async () => {
		io.send('o-test-name');
		io.send(keys.enter);
	};
	setTimeout(() => sendKeystrokes().then(), 5);
	const answers = await prompt.ask(componentName);
	expect(answers.name).toEqual('o-test-name');
	done();
});
```
to
```js
it('should accept a correctly formatted name', async () => {
	const sendKeystrokes = async () => {
		io.send('o-test-name');
		io.send(keys.enter);
	};
	setTimeout(async () => await sendKeystrokes(), 5);
	const answers = await prompt.ask(componentName);
	expect(answers.name).toEqual('o-test-name');
});
```

I think the problem is `setTimeot` not being called as async.

2022-08-24 14:44 UTC, akomiqaia commented on .prettierignore
> +!tools/create-component
It already includes it

2022-08-25 10:52 UTC, akomiqaia commented on tools/create-component/__tests__/cli-integration.test.ts
> +function getNixtInstance(
[d9bb63b](https://github.com/Financial-Times/origami/pull/795/commits/d9bb63b74bca7bd0bf7d56cdffbb6c2a0f5cc5ad) I tried to refactor my tests and hopefully this is commit is better?

2022-08-25 10:52 UTC, akomiqaia commented on tools/create-component/__tests__/cli-integration.test.ts
> +		rimraf('./__tests__/o-test-name', done)
[d9bb63b](https://github.com/Financial-Times/origami/pull/795/commits/d9bb63b74bca7bd0bf7d56cdffbb6c2a0f5cc5ad)

2022-08-30 16:15 UTC, notlee requested changes
Done some manual testing and found just a few small issues remaining!

2022-08-30 16:15 UTC, notlee commented on tools/create-component/src/templates/main.js.ejs
> +import <%- props.camelCase(props.name) %> from './src/js/<%- props.withoutPrefix(props.name) %>.js';
```suggestion
import <%- props.camelCase(props.name) %> from './src/js/<%- props.name %>.js';
```
<img width="1032" alt="Screenshot 2022-08-30 at 16 59 51 1" src="https://user-images.githubusercontent.com/10405691/187485001-53de3c53-002c-4f76-b8ef-6caab1d9b4a5.png">

2022-08-30 16:15 UTC, notlee commented on tools/create-component/src/commands/create-component.ts
> +		);
Nice :) The watch command or storybook would be more helpful for local dev though, as they both listen to changes? 

```suggestion
		print.highlight(
			`npm run watch -w components/${props.name}`
		);
		print.info('or');
		print.highlight(
			`npm run storybook`
		);
```

2022-08-30 16:15 UTC, notlee commented on tools/create-component/src/templates/test/<name>.test.js.ejs
> +import <%= className %> from '../../main.js';
Looks like this is going back one too many directories:

```suggestion
import <%= className %> from '../main.js';
```

2022-08-30 16:15 UTC, notlee commented on tools/create-component/src/templates/test/helpers/fixtures.js.ejs
> +		<div class="<%= props.name %> " data-o-component="<%= props.name %> " id="element"></div>
Boilerplate tests (`npm run test -w components/o-thing`) fail due to the extra space trailing the `data-o-component` value.

```suggestion
		<div class="<%= props.name %>" data-o-component="<%= props.name %>" id="element"></div>
```

2022-08-31 14:46 UTC, notlee approved these changes
🙌

2022-09-01 08:56 UTC, merged