517 dac date error handling
Financial-Times/origami pull request #848
Opened 2022-10-14 14:15 UTC by akomiqaia

2022-10-17 13:53 UTC, akomiqaia commented on components/o-forms/test/input.test.js
> +			dispatch('blur', dateField);
The new validation checks if the date itself is valid rather than if input pattern matches regex patterns defined before so I had to modify the tests a bit to pass them.

2022-10-21 08:21 UTC, notlee requested changes

2022-10-21 08:21 UTC, notlee commented on components/o-forms/src/js/input.js
> +
The `Input` class seems to have a lot of responsibilities. It looks like it's intended to represent a single html `input` (not an `.o-forms__input` element, which may contain multiple html `inputs`). So it's unexpected that it checks the validity of inputs other than itself (date, month, year) and then modifies its parent elements.

Have you considered returning a boolean value here to indicate the  individual html `input`'s validity, and moving everything else to `forms.js`? We could use [validateFormInputs](https://github.com/Financial-Times/origami/blob/38586847f0160fa43bd298fcda51a83e95a71d41/components/o-forms/src/js/forms.js#L119) to determine the overall `.o-forms__input` validity based and toggle classes

2022-10-21 08:21 UTC, notlee commented on components/o-forms/src/js/input.js
> +		const [date, month, year] = Array.from(elements).map(element => element.value);
What if a user has made a mistake in their html and the elements aren't found?

2022-10-21 08:21 UTC, notlee commented on components/o-forms/src/js/input.js
> +	validateDate() {
Kinda related, it looks like we've lost the red border as the css is using the `:invalid` selector to highlight only the invalid `inputs`within `.o-forms-input`.

`.o-forms-input--invalid :invalid:not(:disabled)`

<img width="377" alt="Screenshot 2022-10-21 at 09 18 02" src="https://user-images.githubusercontent.com/10405691/197148297-735f6304-f0cf-489f-9229-48c456a053b6.png">

2022-10-21 08:21 UTC, notlee commented on components/o-forms/src/js/input.js
> +		const dateObj = Date.parse(`${date}/${month}/${year}`);
Hmmm something isn't quite right here!

12th Dec is okay?
<img width="177" alt="Screenshot 2022-10-21 at 09 15 15" src="https://user-images.githubusercontent.com/10405691/197148654-b86ee7ad-09fc-4ced-9e96-fc874238c68c.png">

But 13th isn't?
<img width="381" alt="Screenshot 2022-10-21 at 09 14 59" src="https://user-images.githubusercontent.com/10405691/197148662-1eb17d39-3c05-40ab-ae5f-25bdc696c4d9.png">

2022-10-21 08:23 UTC, notlee commented on components/o-forms/src/js/input.js
> +		const [date, month, year] = Array.from(elements).map(element => element.value);
`alert('Not like that!')` 😂 ?

2022-10-26 16:28 UTC, akomiqaia commented on components/o-forms/README.md
> +			<input id="date" class="o-forms-input__day-part" type="text" inputmode="numeric" name="my-date" aria-label="Day (DD)"/>
that is a good point. I will bring them back but I might need to update JS as well so is we are running JS we can remove pattern attribute from input elements. Also some of this regex needs updating I think last time I tried to test it regex was a bit wrong.

2022-10-27 12:07 UTC, akomiqaia commented on components/o-forms/src/js/input.js
> +
maybe I misunderstood what you meant by this comment and somewhere I do agree with this explanation. But Date input is 3 different inputs that we want to look at it as one. I have been looking at the code and it seems like form.js `validateFormInputs` runs on submit rather than each update of an input. We could update code but then checking whole form validity every-time we type something does not sound good.

2022-10-27 12:24 UTC, akomiqaia commented on components/o-forms/src/js/input.js
> +		const [date, month, year] = Array.from(elements).map(element => element.value);
that is good point. Also jsut thinking about edge cases. Do we have use cases when our date fields are used only to get month and year. The code that i wrote will validate dates only that have all 3 inputs presented in the markup. It will fail to validate `12(mm) 2022(yyyy)` or `dd mm` inputs. should we take this into consideration?

2022-10-27 12:25 UTC, akomiqaia commented on components/o-forms/src/js/input.js
> +		const dateObj = Date.parse(`${date}/${month}/${year}`);
`Date.parse` seems not to like `date/month/year` order and instead it expects it to be `month/date/year`.

2022-10-31 15:04 UTC, notlee commented on components/o-forms/src/js/input.js
> +		const dateObj = Date.parse(`${date}/${month}/${year}`);
Ah okay. Looks like parse behaviour for [non-standard date strings could vary per browser](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#fall-back_to_implementation-specific_date_formats).  Looks like we'll want to [pass in YYYY-MM-DD](https://tc39.es/ecma262/#sec-date-time-string-format)?

2022-10-31 15:27 UTC, notlee commented on components/o-forms/src/js/input.js
> +
>Date input is 3 different inputs that we want to look at it as one

Yeah that's why this has become a bit (more) confusing. Until now `input.js` represented validation for only one html `input`. Not a set of html inputs working together for one `.o-forms__input`. 

>I have been looking at the code and it seems like form.js validateFormInputs runs on submit rather than each update of an input.
>We could update code but then checking whole form validity every-time we type something does not sound good.

Good spot, I didn't notice that, we still want to check validity of form fields as they're being modified at the moment so my suggestion is no good.

Refactoring without a breaking change is difficult because Inputs are passed through Forms publicly as [Forms.prototype.formInputs](https://github.com/Financial-Times/origami/blob/38586847f0160fa43bd298fcda51a83e95a71d41/components/o-forms/src/js/forms.js#L18). Let's chat through some options (maybe we plan for a future major release)

2022-11-08 09:29 UTC, notlee approved these changes

2022-11-08 10:20 UTC, merged