backstage: stop oForms initialising many times to avoid multiple instances of error summaries
Financial-Times/origami pull request #882
Opened 2022-11-10 12:39 UTC by akomiqaia

closes #500 

according to the DAC report, users were getting multiple instances of error summaries. This was a bug that was introduced in version o-autocomplete 1.6.1. The reason seems to be dispatching `o.DOMContentLoaded` events from demo JS files.

2022-11-30 16:44 UTC, notlee requested changes

2022-11-30 16:44 UTC, notlee commented on components/o-forms/src/js/forms.js
> +		return null;
Previously `formInputs` was always an array, but now may be `null`. As a public property a user may rely on this being an array, for example calling `forEach`, and so this could break their code – we don't do a good job of documenting types in Origami components and should look to improve that 😬 

Instead we could return an empty array to indicate no form fields have been found.
```suggestion
		return [];
```

2022-11-30 16:44 UTC, notlee commented on components/o-forms/src/js/forms.js
> +		if (this.form) {
Little tip for the future, I like to return early. It avoids indenting the main body of a function :)

```js
if(!this.form) {
    return [];
}

// everything else
// everything else
// everything else
// everything else
// e.g another condition
if(thing) {
    console.log('hello');
}
```

vs

```js
if(this.form) {
    // everything else
    // everything else
   // everything else
   // everything else
   if(thing) {
        console.log('hello');
    }
}

return [];

```

2022-11-30 16:44 UTC, notlee commented on components/o-forms/src/js/forms.js
> +		this._formInputsCache = null;
```suggestion
		this._formInputsCache = [];
```

2022-11-30 16:44 UTC, notlee commented on components/o-forms/test/forms.test.js
> +
Nice to see tests for this :)

2022-12-05 11:48 UTC, akomiqaia commented on components/o-forms/src/js/forms.js
> +		if (this.form) {
this is a good suggestion. Thanks

2022-12-05 11:49 UTC, akomiqaia commented on components/o-forms/src/js/forms.js
> +		if (this.form) {
[f8dc967](https://github.com/Financial-Times/origami/pull/882/commits/f8dc9679c069c92d421be5fb609d64cf9d2142d3)

2022-12-05 12:03 UTC, akomiqaia commented on components/o-forms/src/js/forms.js
> +		this._formInputsCache = null;
This is part of `destroy()` function. should this remain null?

2022-12-08 11:36 UTC, notlee approved these changes

2022-12-08 12:04 UTC, merged